### ISSUE TITLE
Add "select number of images" for Verify Page

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#104]
Currently, the Verify Page auto loads images when user reaches the bottom of the page. 
![Screenshot (49)](https://user-images.githubusercontent.com/25363572/67046125-1a866f00-f0dc-11e9-8292-68926f64be91.png)

The desired function is the same as the function displayed on the trees page as shown below. 

 ![Screenshot (50)_LI](https://user-images.githubusercontent.com/25363572/67045559-01c98980-f0db-11e9-9fdb-84324c9e9dc8.jpg)

This is the Verify page that should be modified.
![Screenshot (52)](https://user-images.githubusercontent.com/25363572/67045933-b794d800-f0db-11e9-813b-54795d935035.png)

**Comment by david-mike** [comment]
I will take this.

**Comment by qdcheng1** [comment]
Are we going to implement this feature for v2.0?
