### ISSUE TITLE
Establish a link to tree on tree map

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#107]
Each tree should have a link to the tree map. 

When using the filter there should be an option to view the filtered trees on the map. This could/should be done with a call to the webmap API. (same sql statement)

**Comment by sebastiangaertner** [comment]
Establish the link to the tree on the TreeID. This is low hanging fruit: a _blank open in new window link with tree id.

**Comment by Davidezrajay** [comment]
#66

**Comment by sjaymoon15** [comment]
PR #122 for the issue has been merged to master. This issue is probably good to be closed now.

**Comment by sebastiangaertner** [comment]
Any chance we can get this in the live system?
