### ISSUE TITLE
Modify rejection workflow to capture rejection reason

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-api#109]
![image](https://user-images.githubusercontent.com/364622/68522050-ee35bc80-025b-11ea-8b86-f20f0d7d6b94.png)

We would like 4 buttons instead of just 2.  The ‘reject’ will be replaced by 3 different buttons.  The ‘Approve’ will stay the same.  

The 3 buttons will be 
Not a Tree
Duplicate
Blurry Image

These will be reported to the server by both setting the ‘active’ column to false, as well as sending a field named ‘reject_reason’

The values for reject_reason are
not_tree
duplicate
blurry_image

The developer database has been updated with the reject_reason column, which is an enumerated type with the values listed above. 

The Loopback API has NOT been updated yet.  The trees model file will need to be extended to capture this new column, which is of type ‘reject_reason’

**Comment by qdcheng1** [comment]
Can I take this?
