### ISSUE TITLE
Greenstand-TreeTracker-Admin-Favicon

### ISSUE THREAD

**Issue by NickSiena** [Greenstand/treetracker-admin-api#115]
![faviconTreeTracker](https://user-images.githubusercontent.com/37937337/70398484-fd8a6000-19e9-11ea-96b3-d94942e89482.png)

**Comment by Davidezrajay** [comment]
@NickSiena, I am closing this as you opened a duplicate issue... Update favicon #80

**Comment by NickSiena** [comment]
Hi Ezra,
I thought that that's what you told me to do with Favicon that's why I posted it as a new pull request.
Sorry. Thank you.

Nick Siena
CompTIA Linux+ Candidate, LSSYBTech Entrepreneur
(585)236-7796 (Mobile)
Penfield, NY 

    On Tuesday, December 10, 2019, 11:11:32 PM EST, DavidEzraJay <notifications@github.com> wrote:  
 
 
@NickSiena, I am closing this as you opened a duplicate issue... Update favicon #80
