### ISSUE TITLE
Add 'planter_id' and 'device_id' to tree

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#116]
Please add 'planter_id' and 'device_id' to each tree. 

This will speed up the tree verification. Currently every tree we need to know about, we are searching for the tree in the data base to find the 'planter_id'
Note: The 'user_id' has been changed to the 'planter_id' in the database

![Screenshot (63)](https://user-images.githubusercontent.com/25363572/70602515-16894180-1ba1-11ea-91e5-d0c802317fed.png)

**Comment by dadiorchen** [comment]
@Davidezrajay what does this mean: "Please add 'planter_id' and 'device_id' to each tree."? You what to add the planter_id and device_id information to every tree panel box? just like the tree id?

**Comment by Davidezrajay** [comment]
Correct. Every tree panel box should have:
1. tree_id
2. planter_id 
3. device_id

**Comment by dadiorchen** [comment]
story point estimate: 1 Hr

**Comment by wildaces215** [comment]
@Davidezrajay Is it safe to assume from the picture that Tree # 210094 is the tree_id??

**Comment by Davidezrajay** [comment]
@wildaces215 that is correct. Sorry for not clarifying this. 

Thank you @dadiorchen for completing this ticket!
