### ISSUE TITLE
Add 'unselect' feature to image preview

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#121]
**Add to the ability to 'unselect' images in the multi-image select feature.** This is the ability to deselect several image within the selected range by holding 'cmd/ctrl' and clicking on them, while the initial range selection persists.

Current Functionality on the image view panel: 
- Select one image = click an image
- select a range of images = selecting first image in the range, then holding 'ctrl' and 'shift' select the last image in the range. 
- Unselect all images = release the shift key, and click an image,

**Comment by dadiorchen** [comment]
@Davidezrajay need to correct you something, currently, the rule is: click an image to select a single one, then hold shift and click another one to select a range, just like the way in windows explorer and macOs finder

**Comment by dadiorchen** [comment]
and if now release the shift key, and click an image, then, will cancel all the range and just select the single image which you just clicked

**Comment by qdcheng1** [comment]
I take this.
