### ISSUE TITLE
Hover over and select an image 

### ISSUE THREAD

**Issue by qdcheng1** [Greenstand/treetracker-admin-api#136]
Implement effects of hovering over an image and selecting an image.
![hover](https://user-images.githubusercontent.com/32751656/74569172-c3888d80-4f47-11ea-80ff-65607324d628.jpg)

**Comment by gracewylu** [comment]
I'm interested in working on this! Unclear on exactly what the hover over effect exactly is? Also is selecting an image essentially adding a light blue border around the Card?
