### ISSUE TITLE
Reject tab side panel

### ISSUE THREAD

**Issue by qdcheng1** [Greenstand/treetracker-admin-api#139]
To reject a selected image the user selects the image(s) and appropriate tags under the "Reject" tab and selects "submit." 

The tags and specie info will be sent to database. (Blocked by https://github.com/Greenstand/treetracker-database/issues/17)

- Images are rejected based on the tags. 
- Specie information is optional. 

List of reject tags: "Not a tree, Not an approved tree, blurry photo, Dead, duplicate photo, flag user! Flag tree for contact/review"

### Existing functionality:
- Rejecting a `tree_id` changes the `active` field in the `trees` table from `true` to `false` (Note: this removes the tree from the tree tracker map) 
- Rejecting a `tree_id` changes the `approved` field in the `trees` table from `true` to `false` (Note: this removes the tree from the tree tracker map) 

![Reject side panel](https://user-images.githubusercontent.com/32751656/74589395-03e11d80-4fd3-11ea-88d6-f88b0d633358.jpg)

**Comment by dadiorchen** [comment]
Finished.
