### ISSUE TITLE
Remove Reject All /Approve all button

### ISSUE THREAD

**Issue by qdcheng1** [Greenstand/treetracker-admin-api#140]
Since the reject/approve is based on tags, we will not support reject all/approve all. 
1. Remove these two buttons.
2. Keep the multiple selection by pressing shift and unselect feature (pressing cmd/ctrl).

**Comment by Davidezrajay** [comment]
@david-mike the Bulk Reject/Bulk Approve should be based on the images selected plus the submit button. We will no longer need the buttons. Perhaps we change this ticket to "Remove the Reject/Approve Buttons"?

**Comment by qdcheng1** [comment]
@Davidezrajay We need to disable the feature of selecting multiple images by pressing shift?

**Comment by Davidezrajay** [comment]
@dadiorchen we will still need to be able to select multiple images at one time. 

I am not sure the best way to do that. But if the shift select is working it may be easy to leave it in there. Actually I see that issue #136 may have another better option?

**Comment by dadiorchen** [comment]
#136 seems like a different case, here I thought you are right, just remove those button, and keep the bulk-select-operation, namely using shift to select multiple trees, and ctrl to select/unselect some single individuals, then press 'submit' to commit the bulk operation.

**Comment by qdcheng1** [comment]
@Davidezrajay @dadiorchen I will remove the Approve all / Reject All button and keep bulk-select-operation.

**Comment by Davidezrajay** [comment]
Perfect! Thanks
