### ISSUE TITLE
Status Dropdown

### ISSUE THREAD

**Issue by qdcheng1** [Greenstand/treetracker-admin-api#141]
Change the dropdown menu.
For status dropdown, there are approved and rejected options in the design doc. Do we need more options, such as "All" , "To Be Determined"? There might be situations in which people only want to see all the trees except the approved and the rejected.

![StatusDropDown](https://user-images.githubusercontent.com/32751656/74590354-9be30500-4fdb-11ea-86f8-ed4966fa3b98.jpg)

**Comment by Davidezrajay** [comment]
Status drop down should should have the following option: 
- None
- Approved
- Rejected
- All 

The default option should be "None"

This should provide the same search options that the current functionality offers. We currently have the following options:
Approved: 
- True
- False
- All
Rejected: 
- True
- False 
- All

![Screenshot (111)](https://user-images.githubusercontent.com/25363572/74722185-8d9a2080-5249-11ea-9f7c-e0ea53f70308.png)
![Screenshot (112)](https://user-images.githubusercontent.com/25363572/74722197-8f63e400-5249-11ea-8b5b-718294355316.png)

**Comment by Davidezrajay** [comment]
Current Functionality has the following options which can be removed:
Approved: 
- True
- False
- All
Rejected: 
- True
- False 
- All

![Screenshot (111)](https://user-images.githubusercontent.com/25363572/74722185-8d9a2080-5249-11ea-9f7c-e0ea53f70308.png)
![Screenshot (112)](https://user-images.githubusercontent.com/25363572/74722197-8f63e400-5249-11ea-8b5b-718294355316.png)

**Comment by Davidezrajay** [comment]
@david-mike I think we should not use the **Status** drop down for this milestone and  replace it with the current functionality which has two drop downs: **Approved** **Rejected** Then the only ticket we will have to create is to move the approved/rejected drop downs to the top and put them where the status field is. This seems like the easiest option. What do you think?

**Comment by qdcheng1** [comment]
@Davidezrajay Sure. We can move the approved/rejected drop downs to the top and think about the status dropdown later in the future.

**Comment by Davidezrajay** [comment]
@david-mike Thank you for this one! Awesome Work
