### ISSUE TITLE
Move the Approved and Rejected Drop downs 

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#142]
Move the **Approved** **Rejected** to where the **Status** drop down is in the latest mock up. 

These are the current buttons: 
![Screenshot (112)](https://user-images.githubusercontent.com/25363572/74726493-9b9f6f80-5250-11ea-8857-72a76315e954.png)
![Screenshot (111)](https://user-images.githubusercontent.com/25363572/74726496-9d693300-5250-11ea-8689-10d27f314774.png)

This is the **Status** drop down that should be replaced. 

![Screenshot (105)](https://user-images.githubusercontent.com/25363572/74726677-ee792700-5250-11ea-95e5-f2816b700328.png)

![StatusDropDown](https://user-images.githubusercontent.com/32751656/74590354-9be30500-4fdb-11ea-86f8-ed4966fa3b98.jpg)

**Comment by dadiorchen** [comment]
@Davidezrajay  can you describe a little more? what do you want to do on this ticket?

**Comment by dadiorchen** [comment]
I am a little confused...
