### ISSUE TITLE
Sort the list of species. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#167]
In version 2, the list of species, in the right-side-panel, and in the filter, the order is messy, should sort the list by alphabet.
<img width="246" alt="Screen Shot 2020-04-28 at 5 10 24 PM" src="https://user-images.githubusercontent.com/5744708/80469473-2f896800-8973-11ea-8230-b01c9aa0d10b.png">
<img width="371" alt="Screen Shot 2020-04-28 at 5 10 08 PM" src="https://user-images.githubusercontent.com/5744708/80469498-3912d000-8973-11ea-8149-43fae265c5db.png">

**Comment by nmcharlton** [comment]
I'll take a look at this.
