### ISSUE TITLE
'Ctrl' Select 

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#169]
Add the ability to select images out of sequence using 'Ctrl' plus select. 

We already have the feature that allows us to select a sting of images using 'shift' select.

**Comment by dadiorchen** [comment]
@david-mike I remember you have finished this, right? Can you check the code? Did we lose it from the master branch? to v2.1?

**Comment by dadiorchen** [comment]
Have solved.
