### ISSUE TITLE
Image Pop Up Logic 

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#170]
The awesome image pops up and expands to show the entire image when the curse is hovered over the image. 

This prevents the image from being selected.

Possible solutions: 

- enable selection of the image from the card
- click to close the pop up
- only open pop up when double clicked

**Comment by dadiorchen** [comment]
@Davidezrajay how about add a button to click to open it? and add a close button on the popup window?
<img width="494" alt="Screen Shot 2020-04-30 at 10 15 42 AM" src="https://user-images.githubusercontent.com/5744708/80665630-98382800-8acc-11ea-933a-8a5392f4cce0.png">

**Comment by Davidezrajay** [comment]
Cool, Lets make a button for the pop up with this icon.

![Picture icon](https://user-images.githubusercontent.com/25363572/80851980-55ac4380-8bd1-11ea-85e8-edd02b9eaf0a.png)

**Comment by dadiorchen** [comment]
Finished.
![Greenstand - Tree Tracker (3)](https://user-images.githubusercontent.com/5744708/80896573-44bf1780-8d22-11ea-8f22-8f1fea97fd18.gif)
