### ISSUE TITLE
Map link direct as per configured

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#172]
Admin panel: map link only directs to treetracker.org, it needs to be configurable to use the map for the environment it's installed on and configured for.

- test.treetracker.org
- Test.treetracker,org, 
- dev.treetracker.org

**Comment by dadiorchen** [comment]
I'd like to append some taks on this ticket:
* Add the feature of Create-react-app env configures. So we can get different settings for different environments. Like:  env.local env.server. env.test
https://create-react-app.dev/docs/adding-custom-environment-variables

**Comment by nmcharlton** [comment]
How is our manual test environment set up?
Do we build the client and deploy that to a test environment?
If this is the case, it's a little trickier to set the webmap URL using the `.env` method, since react-scripts prevents you from overriding `NODE_ENV` to use the test environment.

**Comment by dadiorchen** [comment]
We use ansible to deploy them. 
Yes, we build the client then deploy. But I thought we can set the build ENV to let the client using some special setting for special env? like this: NODE_ENV=3000 npm run build ?

**Comment by nmcharlton** [comment]
You're right.

Although `NODE_ENV` can't be overridden when building with react-scripts, we can directly set variables, or better still, invoke a separate environment file (e.g. for a staging environment such as this).
https://create-react-app.dev/docs/deployment/#customizing-environment-variables-for-arbitrary-build-environments

I'll update the PR to include this option.
