### ISSUE TITLE
Add check box to selected images

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#175]
When an image is selected we should add a check box to it as per the designs. 
 Desired state:
![Screenshot_20200504-111305](https://user-images.githubusercontent.com/25363572/81005199-09901780-8dfa-11ea-926b-547b980c60bc.png)

**Comment by nmcharlton** [comment]
Mind if I take this one?
Can you point me at some sample data to populate the admin panel?
Is there a full set of design material, including style guidance?

**Comment by dadiorchen** [comment]
Hi, @nmcharlton that's great you can deal with this one. Please first install the dev env locally then you can find there are some data in it already. 
We are using MaterialUI, so you need to follow the rule of them.

**Comment by nmcharlton** [comment]
Thanks @dadiorchen.
To get things going I needed to change `variables.js` to point at my local API container as well as adding a valid `treetracker.datasource.json`. I'm using [a version I found on Slack](https://greenstand.slack.com/files/U73TYBBAB/FL2U6N7QE/treetracker.datasource.json) - is this an appropriate data source for development?

**Comment by nmcharlton** [comment]
Are the checkboxes just intended a visual cue to indicate that an image is selected (so can be hidden when not selected) or should a user be able to toggle individual checkboxes as a means of selecting/deselecting images?

**Comment by nmcharlton** [comment]
> Are the checkboxes just intended a visual cue to indicate that an image is selected (so can be hidden when not selected) or should a user be able to toggle individual checkboxes as a means of selecting/deselecting images?

Is this the sort of behaviour expected from this interaction?

![OneDrive_multi-select](https://user-images.githubusercontent.com/5558838/81827819-0c44e800-9531-11ea-8871-709b97e22e28.gif)

**Comment by dadiorchen** [comment]
@nmcharlton Hey, you are right, it's reasonable, just show the checkbox when selected. 

> Thanks @dadiorchen.
> To get things going I needed to change `variables.js` to point at my local API container as well as adding a valid `treetracker.datasource.json`. I'm using [a version I found on Slack](https://greenstand.slack.com/files/U73TYBBAB/FL2U6N7QE/treetracker.datasource.json) - is this an appropriate data source for development?

Yes, it is.

**Comment by dadiorchen** [comment]
Why do you need to change variable to run it? I thought we can use it directly? Whan kind of problem you met?

**Comment by nmcharlton** [comment]
> Why do you need to change variable to run it? I thought we can use it directly? Whan kind of problem you met?

I had to change
```
export const API_ROOT = 'api/admin'
//export const API_ROOT = 'http://localhost:3000/'
```
to
```
//export const API_ROOT = 'api/admin'
export const API_ROOT = 'http://192.168.99.100:3000/'
```
(Note: I'm running Docker Toolbox on an old version of Windows 10 Home.)
