### ISSUE TITLE
Add vertical scroll bar in the tree validation page. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#177]
It's kind of inconvenient without the scroll bar. 
<img width="1204" alt="Screen Shot 2020-05-06 at 5 52 12 PM" src="https://user-images.githubusercontent.com/5744708/81164238-a2718f00-8fc2-11ea-8c0e-37243f6518a7.png">

**Comment by nmcharlton** [comment]
I can take this one.
