### ISSUE TITLE
add css on popup image detail

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#181]
Add class
.MuiDialogActions-spacing{
padding-left: 16px;
padding-right: 16px; 
}

to get nice spacing on the popup info panel.

**Comment by bsbjones27** [comment]
i will take this one. Thanks.

**Comment by bsbjones27** [comment]
is it possible to get a bit more information on this issue? thank you.

**Comment by dadiorchen** [comment]
I thought this is about the appearance of the UI, we need to leave more space around the major content in the popup dialog. Can you find the dialog?

**Comment by bsbjones27** [comment]
yeah, i am having a bit of trouble locating it.  I know there is a dialog box on both the 'verify page' and 'tree page.' I wanted to confirm that the edit needed to be done on the dialog box on the verify page? Thanks.

**Comment by dadiorchen** [comment]
This dialog, and note the arrow I marked.
<img width="1402" alt="Screen Shot 2020-07-22 at 7 41 43 AM" src="https://user-images.githubusercontent.com/5744708/88117940-f87fc700-cbee-11ea-80eb-7727aa07d9cc.png">

**Comment by bsbjones27** [comment]
okay got it.
