### ISSUE TITLE
Populate Planters Tab

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#182]
We can copy the same template from the trees with a few minor changes. 

- [ ] Change the image to pull from the planter image from the `planter table`
- [ ] Change the `Approved true/false` to `Entity_id = true/false` using the `person_id` from the `planter table`
- [ ] Remove Reject box
- [ ] Remove start date and end date boxes

![Screenshot (163)_LI](https://user-images.githubusercontent.com/25363572/81427278-0e5d1000-9107-11ea-8920-ec2902ebd21a.jpg)

**Comment by dadiorchen** [comment]
So we begin to build the planter panel? It's exciting! :)

**Comment by dadiorchen** [comment]
@Davidezrajay How do we display the planter, display the picture of planters? so the layout just looks like the tree page? Or we need to use plain table?

**Comment by Davidezrajay** [comment]
@dadiorchen I think that is easy, we just copy the same layout.

**Comment by dadiorchen** [comment]
@Davidezrajay then we should use the planter's photo to replace the tree picture, right?

**Comment by Davidezrajay** [comment]
Yes

**Comment by sebastiangaertner** [comment]
Exciting indeed. Should we get a UX UI for this as well? I think a list style is better here than the picture based thumbnails. We will def need the filters.

**Comment by Davidezrajay** [comment]
@sebastiangaertner this page is meant to make sure all new users are given a person_id. And this is best down with images

**Comment by dadiorchen** [comment]
And don't blame my new test version about this is ugly, I just don't get planter's photo in the test DB, so most of the picture is just a simple icon there. :)
