### ISSUE TITLE
Replace the table component. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#183]
Currently, we are using table component, mui-datatables, but we found there are many problems and limitations for using it. Like it's hard to change the appearance of it, and customizing something. 
So we decide to change back to use the original MaterialUI table. 
This ticket is about removing the component and changing to MaterialUI table component. 
Any suggestion is welcome.

**Comment by lukasbicus** [comment]
@dadiorchen - how should this table look like? Do you have some designs?

**Comment by dadiorchen** [comment]
This ticket is still valid and open.

**Comment by nmcharlton** [comment]
I can take a look at this.
