### ISSUE TITLE
Adjust the tree picture size to fit the container. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#184]
Currently, every line there are 3 trees displaying, but the size is not so appropriate, need to adjust the size to be as big as possible to fill the space.
<img width="1429" alt="Screen Shot 2020-05-14 at 9 26 35 AM" src="https://user-images.githubusercontent.com/5744708/81882531-92ab0980-95c5-11ea-803f-5a6f7bd8bd57.png">

**Comment by nmcharlton** [comment]
I'll take a look at this one.
This needs a proper responsive grid with sensible breakpoints to keep the images from getting to small or large.
