### ISSUE TITLE
Setting PWA feature for React App to speed up loading.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#185]
Using the PWA feature to cache the app locally, so we can open it faster.

**Comment by elfiyang16** [comment]
@dadiorchen is this not done yet? I saw there's a service worker there already or it's not working?

**Comment by dadiorchen** [comment]
Not yet, as I know, React has some default code for the worker service, but, they are disabled by default, so our works are to open it, and test it works well.

**Comment by dadiorchen** [comment]
https://create-react-app.dev/docs/making-a-progressive-web-app/ about the tech to do so.

**Comment by dadiorchen** [comment]
This ticket is still valid and open

**Comment by nmcharlton** [comment]
I'll grab this one
