### ISSUE TITLE
Main menu button click handler is attached to icon, not button

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-api#188]
Clicking the main menu button in the toolbar only toggles the sidebar menu if you click the icon in the middle of it.
The click handler `handleToggleMenu` is attached to the icon and not the button that contains it.

**Comment by nmcharlton** [comment]
I'm happy to fix this.

**Comment by dadiorchen** [comment]
That great, thanks @nmcharlton !
