### ISSUE TITLE
Document Set Up

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#19]
Please evaluate the documentation and make sure it is complete enough to run. Comment on this ticket if there are problems and create a pull request for any updates to the setup readme. 

If you have errors please note and document the problem/solution.

**Comment by bittricky** [comment]
@Davidezrajay I Had the error when running `./dev/up.sh` command. Resetting up the docker image using the command `./dev/setup.sh` re-imaged the container for me. It comes from `docker` not being able to find where the `repo` address is pointing to.

**Comment by ZavenArra** [comment]
OP probably didn't run ./dev/setup.sh before running ./dev/up.sh ?
