### ISSUE TITLE
Build a nav bar component. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#208]
Currently, we need to copy the navbar on every page: 
<img width="1437" alt="Screen Shot 2020-05-23 at 10 18 04 AM" src="https://user-images.githubusercontent.com/5744708/82719626-e5c83f00-9cde-11ea-827f-6bda35ada3d3.png">
So it would be better to build a component to re-use it. 
The problem is: we have some "special" part in the navbar when displayed on different pages. Like this one, the filter is different from "verify" page. 
<img width="1437" alt="Screen Shot 2020-05-23 at 10 18 17 AM" src="https://user-images.githubusercontent.com/5744708/82719659-288a1700-9cdf-11ea-90b8-e7c7bd3b8728.png">
So this component is not just a static one, it should have some dynamic content in it.

**Comment by nmcharlton** [comment]
I'm happy to take this one on.

**Comment by dadiorchen** [comment]
I think you are the best one to handle this ;) This UX exercise is kind of weird
