### ISSUE TITLE
Docker dev environment broken

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-api#209]
Following improvements introduced in #206 the Docker dev configuration stopped working for me (using Docker Toolbox).
Docker maps external port 3001 to internal port 3000, but the web client start script sets the internal port to 3001.

**Comment by lukasbicus** [comment]
> Following improvements introduced in #206 the Docker dev configuration stopped working for me (using Docker Toolbox).
> Docker maps external port 3001 to internal port 3000, but the web client start script sets the internal port to 3001.

@nmcharlton - just update `package.json`
instead of:
```
...
"start": "PORT=3001 react-scripts start",
```
use:
```
...
"start": "react-scripts start",
```

**Comment by dadiorchen** [comment]
@nmcharlton You are right, can you fix this problem? Thanks!
