### ISSUE TITLE
Add Tags Option

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#212]
A box like a the species field box for tags
These tags will be in a field in the Trees table and will be used like hash tags

**Comment by nmcharlton** [comment]
I can take this one.

@Davidezrajay Will the tags be assigned when a tree is accepted/rejected?

I notice that the term 'tags' appears to be used to refer more broadly to the details attached to a tree when it is approved/rejected. If we use 'tags' for this new feature as well, we'll be introducing confusion.

Is there a different term we could use to refer to either concept?

**Comment by nmcharlton** [comment]
Proposed UI for entering tags (using https://github.com/TeamWertarbyte/material-ui-chip-input).

![Tree-tags-input-UI](https://user-images.githubusercontent.com/5558838/84391028-4d8fec80-abf0-11ea-93dc-be2927dc955a.gif)

Previously used tags are stored and queried as the user types their tag.
Suggestions appear in a list below the input.

Depending on the intended use we could enhance the UX by providing quick access to a few of the most commonly used tags.

**Comment by ZavenArra** [comment]
Implement in database using a cross table

new tables:
tag: id (int), tag_name (string), active (bool default true), public (bool default true)
tree_tag: id, tree_id, tag_id


'public' tags would be ones that can be accessed via the public map, which is the default.

**Comment by nmcharlton** [comment]
Regarding @Davidezrajay's comments on this:

> We are looking for ways to work with this data using tags. There are requests to make maps with tags, and they can be used to hone in our data analysis pipeline. We currently have `morphology` `age` `species` `capture_approval_tag` and  `rejection_reason.` Could we make them all tag based?

Each of these fields could be a special case of `tag` with a pre-defined value. The UI could stay as it is (radio buttons for options and free text for additional tags) but everything would be added as an entry in the `tree_tag` table to facilitate queries.

@deepwinter: Do you think it's worth adding a column to the `tag` table to indicate if the tag is one of these special types? This would also require a new `tag_type` enum.
I'm not sure if this is necessary - using the tag name by itself might be enough.
