### ISSUE TITLE
Duplicate and blur selections don't work

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#213]
These are on the reject reasons on side of the admin panel. Unable to select the reasons when clicking on the reject reasons `Blurry Photo` `dead` `duplicate photo` `flag user` flag tree for contact/review.`

`Not a tree` and `not an approved tree` buttons work wonderfully!

**Comment by nmcharlton** [comment]
I'll grab this one if no one objects. Looks pretty trivial.
