### ISSUE TITLE
Design tags and data display in the tree image popup 

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#214]
Any information previously displayed in the tree filed should be added to pop card.

**Comment by dadiorchen** [comment]
@Davidezrajay does this satisfy you? I don't know what's the tree filed you mentioned.

![image](https://user-images.githubusercontent.com/5744708/84221467-e139be00-ab07-11ea-8784-53a40623212b.png)


Demo: https://14bvv4.axshare.com/#p=verify

**Comment by Davidezrajay** [comment]
yes

**Comment by nmcharlton** [comment]
I can take this one.
