### ISSUE TITLE
Planters -> Filter: layout adjustment. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#218]
Need some padding space, the form input is too close to the bottom line. 
<img width="737" alt="Screen Shot 2020-05-26 at 2 03 46 PM" src="https://user-images.githubusercontent.com/5744708/82865691-efa9a680-9f59-11ea-965a-63d299e9a0a2.png">

**Comment by jun383914** [comment]
I want to take this one. :)
