### ISSUE TITLE
Planters -> pagination bug.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#219]
The pagination can not work correctly. When using filter, the pagination's status is wrong. See below picture, here is obviously just one page, but the pagination shows many. 
And maybe need to change the pagination, currently, it's using Pagination, maybe TablePaginition is better. 
<img width="1430" alt="Screen Shot 2020-05-26 at 2 09 59 PM" src="https://user-images.githubusercontent.com/5744708/82865991-9d1cba00-9f5a-11ea-88b4-86b3e357cf73.png">

**Comment by nmcharlton** [comment]
I'll grab this one as it's so similar to the other bits I've been doing.

**Comment by nmcharlton** [comment]
I agree that `TablePagination` would be better for consistency with the other pages, and gives you a nice count of the matching records, but is less convenient if users will want to jump to a specific page.
