### ISSUE TITLE
Planter detail add information. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#220]
On the detail drawer of the planter, need to add more information: organization_id.

<img width="1440" alt="Screen Shot 2020-05-26 at 2 10 53 PM" src="https://user-images.githubusercontent.com/5744708/82866301-36e46700-9f5b-11ea-8847-8dae51dee693.png">

**Comment by bsbjones27** [comment]
@dadiorchen, I would like to work on this one.
