### ISSUE TITLE
Planters -> Filter add filter criteria: organization_id

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#221]
Need to add a new filter criteria: organization_id.
<img width="737" alt="Screen Shot 2020-05-26 at 2 03 46 PM" src="https://user-images.githubusercontent.com/5744708/82866505-9e021b80-9f5b-11ea-913d-35de3191acb4.png">

**Comment by bsbjones27** [comment]
I can take this one. Thank you.
