### ISSUE TITLE
Add search by Tags and Species to Tree Verify Page

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#224]
Ideally we would be able to search by trees so we can get a list/ review specific species.

**Comment by dadiorchen** [comment]
I'd like to work on the UX for this one, @Davidezrajay your intention is to add search functionality on the VERITY page, not the TREES page?  They are different entries on the menu item.

**Comment by dadiorchen** [comment]
Now we have species as a condition in the filter on the Verify page, is that what you want?

**Comment by Davidezrajay** [comment]
yes. Perfect.

**Comment by nmcharlton** [comment]
I'll get started on a 'tag' filter to close this one off.

**Comment by nmcharlton** [comment]
@Davidezrajay @dadiorchen
This issue was created before arbitrary tree tags could be added in the 'Additional tags' field.
Was the intention to filter by those in the Verify page?

**Comment by Davidezrajay** [comment]
@nmcharlton Yes, the goal is to filter tags by the Verify page. 

I can be the same search box as the species.
