### ISSUE TITLE
User System: password need to be hashed before saving into DB. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#227]
Currently, the API server didn't hash the password created by user, so it's not appropriate to put raw password into DB directly.
DB tables: admin_user, field: password_hash + salt 
<img width="1440" alt="Screen Shot 2020-06-01 at 5 14 33 PM" src="https://user-images.githubusercontent.com/5744708/83394609-74e5fd00-a42b-11ea-827a-bdb33784bc3b.png">

**Comment by elfiyang16** [comment]
@dadiorchen it seems so! But a few questions before jumping in: 
- are you on an advanced branch comparing to the current master as I can see there're significant differences in features e.g. the extra User Manager tab (see current screenshot on master below). 
![image](https://user-images.githubusercontent.com/29664811/83453388-534c3c00-a452-11ea-9d87-371d199826f3.png)
- If a user register/login is enabled in `React`, does it mean correspondent changes are made to the server app as well? But now in `planter.model` I only see `pwd_reset_required` and `salt` ...

Happy to jump on a call if you are happy to. I'm in UK time so afternoon/night Beijing time should work for me :))

**Comment by dadiorchen** [comment]
@elfiyang16 I just merged code to master yesterday, so the newest code about the user system are all in master.
What do you mean about something in the planter.model? Now, all the models will bring auth token to request the API from server, the token will be checked by API server.  
Maybe you are checking some old code? 
I'm almost online in day time, just call me on slack :)

**Comment by elfiyang16** [comment]
Thanks for the info on slack - just to confirm that i will take the issue :)

**Comment by dadiorchen** [comment]
Thank you for your work.
