### ISSUE TITLE
User System: need to complete some account detail information.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#228]
On the 'account' page:
<img width="1440" alt="Screen Shot 2020-06-01 at 5 16 00 PM" src="https://user-images.githubusercontent.com/5744708/83394809-cabaa500-a42b-11ea-9539-c8eb6e92ab02.png">

**Comment by bsbjones27** [comment]
I (Brandon Jones) will be working on this issue. Anyone is welcome to join. Thanks.
