### ISSUE TITLE
User System: need to add 'delete user' function.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#229]
Need to add 'delete user' function, on the user manager page. 
<img width="1440" alt="Screen Shot 2020-06-01 at 5 18 41 PM" src="https://user-images.githubusercontent.com/5744708/83395000-1e2cf300-a42c-11ea-97e6-0aeb6c074749.png">

**Comment by ericlvogt** [comment]
I can take this one
