### ISSUE TITLE
User System: need to display users 'active' status on the list. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#230]
<img width="1552" alt="Screen Shot 2020-06-01 at 5 20 52 PM" src="https://user-images.githubusercontent.com/5744708/83395182-6f3ce700-a42c-11ea-8d2c-335949ade35c.png">
active field type is boolean, should be displayed as: active, inactive.

**Comment by elfiyang16** [comment]
I take this

**Comment by nmcharlton** [comment]
This fix appears to have disappeared somewhere, although I can't figure out where.
The regression doesn't appear in [the commit history for the file](https://github.com/Greenstand/treetracker-admin/commits/master/client/src/components/Users.js).

See #285 for the fix that needs to be made (again).

**Comment by BirdTho** [comment]
@dadiorchen What's up with this one? Mind if I take it, as well as #231 ?

**Comment by nmcharlton** [comment]
@BirdTho Go for it!
