### ISSUE TITLE
User System: administrator can set user's active status.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#231]
<img width="1552" alt="Screen Shot 2020-06-01 at 5 27 56 PM" src="https://user-images.githubusercontent.com/5744708/83395724-60a2ff80-a42d-11ea-8376-740e9a50d562.png">

**Comment by elfiyang16** [comment]
well it seems this one is the precedent of issue 230 or at least these 2 have to be dealt in similar ways in terms of a new column need to be added to database first

**Comment by dadiorchen** [comment]
No need to add a new column, the column is: active.

**Comment by BirdTho** [comment]
this is ready, I think. See PR #401 

![User status editing](https://user-images.githubusercontent.com/10731513/93692763-e2399e80-faab-11ea-9a52-7348d910ab7f.png)
