### ISSUE TITLE
User System: Add validation for user detail form fields. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#236]
Need to add some validation for this form:
* username is required. (For new user adding)
* Role is required, at least chose one role for the user. 

Tips: Material-UI textfield component has some convenient props for error message displaying. https://material-ui.com/components/text-fields/#validation

<img width="1552" alt="Screen Shot 2020-06-01 at 5 48 04 PM" src="https://user-images.githubusercontent.com/5744708/83397347-12433000-a430-11ea-95b2-81e3516c5554.png">

**Comment by ericlvogt** [comment]
I can take this.
