### ISSUE TITLE
User System: Generate a random password automatically to help set password. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#237]
When user opens the 'generate password' dialog, should automatically populate a random password into the input. Something like: a2d3d9s2 
<img width="1552" alt="Screen Shot 2020-06-01 at 5 52 16 PM" src="https://user-images.githubusercontent.com/5744708/83397965-102da100-a431-11ea-8d55-0dffcfa32603.png">

**Comment by elfiyang16** [comment]
@dadiorchen a bit confused by the flow:
- currently user can't register on Login page
- admin create user 
- admin generate password for user through the modal shown above
- password sent to BE and written into DB
- when user login, how does s/he know the password then?

does this link the yet-to-be-implemented functionality re admin "copy paste" the password and send to the user off the platform?

Also, the help text : "We automatically generated a password for you, if you don't like it, you can put a new one by yourself." -- "you" is referring to the admin not the user right?
