### ISSUE TITLE
User System: add validation on login page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#239]
Please add some validation on the login page:
* username: is required.
* password: is required.

tips: Material-ui textfield component has some convenient props to display error message: https://material-ui.com/components/text-fields/#validation 

<img width="1552" alt="Screen Shot 2020-06-01 at 5 58 46 PM" src="https://user-images.githubusercontent.com/5744708/83398348-c5605900-a431-11ea-9457-b9ef92caa0ad.png">

**Comment by elfiyang16** [comment]
I will take this.
