### ISSUE TITLE
Audit Log

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#241]
Create a user audit log for all activities a user does. This is a basic QA function that will allow us to see who "rejected" or "Accepted" each tree and with which tags they add.

**Comment by dadiorchen** [comment]
I will work out UX for this first, then split it to tickets.

**Comment by Davidezrajay** [comment]
@dadiorchen This can be an internal log. It doesn't need to be built into the admin panel as long at it is in the database it will be good.

**Comment by nmcharlton** [comment]
Auditing for user login attempts and tree verifications by non-organization users was introduced to `master` in #321.
Auditing tree verification by organzation users is not yet implemented.

**Comment by nmcharlton** [comment]
I'm going to close this one as audit logging functionality has been added.
I've raised #491 to cover missing organization trees.
