### ISSUE TITLE
Create Tree Scrubber 

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#25]
M x M Scoallable view of incoming images, with the ability to flag images that are invalid.

**Comment by ZavenArra** [comment]
@thiagodemellobueno said:
> We have a husk component for ImageScrubberActions.
> At first it may just have:
> 
> 1. A count of items selected
> 2. A "delete" button (deactivate tree)
> 3. Possibly a "we just marked X trees inactive. " option
