### ISSUE TITLE
User System: increase User password strength 

### ISSUE THREAD

**Issue by elfiyang16** [Greenstand/treetracker-admin-api#254]
Increase user password strength when generate password 

Linked issue: 
- https://github.com/Greenstand/treetracker-admin/issues/237#issue-628306230
- https://github.com/Greenstand/treetracker-admin/issues/235#issue-628300485 (Pull Request [here](https://github.com/Greenstand/treetracker-admin/pull/252#issue-428753693))

Suggest using **zxcvbn** package to assess the password strength (you may want to code splitting due to the module size)

Scenario
- Given when I'm a User 
- When I change my password
- I want to see an indicator of my password strength
- Update to 10 character minimum

Rating below
Use ZXCVBN for Password Estimation
Rating 0 - 2 are weak (fail)
Rating 3 is strong
Rating 4 is very strong

Relevant resources:
 https://github.com/dropbox/zxcvbn
https://upmostly.com/tutorials/build-a-password-strength-meter-react
https://css-tricks.com/password-strength-meter/
https://webpack.js.org/guides/lazy-loading/

**Comment by dadiorchen** [comment]
Hey, this is a good idea!
