### ISSUE TITLE
User System, Role mechanism refactor

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#258]
Currently, for checking the user permission, we just simply are using role name to check the user permission, it isn't flexible, we need to refactor the code of checking user permission, to use more granular permission items to do so. 
Please check this document for getting some sense of this.
https://docs.google.com/document/d/1C-Doe5WNgVi9PiaKRhGrxKnE_xMOlcR9lS5IMV4FkA4/edit?usp=sharing
There is a policy.js file under client and server respectively. We can use it to check the user permission. 
Note, we have a init() function in auth.js, we should add the policy JSON into this part to let the policies get initialized.

**Comment by elfiyang16** [comment]
This is very interesting, but i need a bit more information on this -- contact you on slack
