### ISSUE TITLE
Login page, a tiny UX problem.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#259]
When we open the login page, without any interaction, the login form would display some warning shown below. We'd better hidden the warning first, and after the user made some interaction, like focus and blur the input box, then, the warning would show up. 
![image](https://user-images.githubusercontent.com/5744708/84217255-38d32c00-aafe-11ea-8d5a-a6745cd9ed15.png)

**Comment by elfiyang16** [comment]
I will take this
