### ISSUE TITLE
Tree verify: press CTRL/CMD to select trees. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#262]
Currently, our multiple-selection rule is:
* click tree to select a single tree.
* press SHIFT and click to select consecutive trees. 
* press CMD/CTRL and click to unselect one single tree.

Now, in the real practice, operators want to select trees one by one and they are consecutive. 
So, I suggest to add: 
* press CMD/CTRL to select one single tree.

This means: if the tree was selected, then, press CMD/CTRL to unselect it. otherwise, select it.

**Comment by nmcharlton** [comment]
I'll take a look at this one.
