### ISSUE TITLE
Flash when login. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#275]
![Untitled](https://user-images.githubusercontent.com/5744708/85188417-de458700-b2d8-11ea-854f-fb93c4b74862.gif)

If we selected 'remember me', then when we open the admin panel, there is a flash of the login form before jumping to the home page, we need to hide the login form (or displaying a spin animation) to avoid this flash.

**Comment by elfiyang16** [comment]
I take this :)
