### ISSUE TITLE
test admin filters tree id

### ISSUE THREAD

**Issue by Elmoutcault** [Greenstand/treetracker-admin-api#280]
when using the tree id filter, I will put the tree number in space and press apply filter, then will say "Sorry, no matching records found" then to get back to filter page have to press "clear filters" button

**Comment by dadiorchen** [comment]
@Elmoutcault the issue is about the 'tree' page, right? This page:
![image](https://user-images.githubusercontent.com/5744708/85484441-6ee1d700-b5f9-11ea-89c0-1cd991d2eb67.png)

**Comment by Elmoutcault** [comment]
@dadiorchen yes, that page

**Comment by dadiorchen** [comment]
I will fix this.

**Comment by dadiorchen** [comment]
@Elmoutcault please help to test this issue again, I have solved it.

**Comment by Elmoutcault** [comment]
is working great so far now! so far the problem has not occurred. goes straight to tree number immediately. thanks @dadiorchen
