### ISSUE TITLE
test admin trees section filter issues

### ISSUE THREAD

**Issue by Elmoutcault** [Greenstand/treetracker-admin-api#281]
trying to use the filters, As is in testing stage and most areas say "pending" it is difficult to say that they do not all work when asking for specifics and pressing "apply filters" but so far at moment the only change that will come up, get results is if I use the date (start date/end date) filter.  if I try to use any other filter, that doesnt say "pending" on the graph, is yielding no results other than "sorry, no matching records found" which at moment the only sections that do not say "pending" other than date are the tree number and status. on status it says "planted" but if I go under status on filter section, select "planted" and press apply filters, the result is "sorry, no records found"

**Comment by dadiorchen** [comment]
Thanks, @Elmoutcault I will fix this. 
And seems like the 'status' has been deprecated in this new version, it has been replaced by our new tags system:  
in the rejection selection, you can find options like: not a tree, blurry photo, and so on. So I will remove the 'status' column in the table.

**Comment by dadiorchen** [comment]
@Elmoutcault please test this problem again.
