### ISSUE TITLE
test.admin user manager duplication of roles

### ISSUE THREAD

**Issue by Elmoutcault** [Greenstand/treetracker-admin-api#284]
when in user manager page, and press add new user, there are options for what that user can do, on my end i have options of admin, tree manager, and plant manager. when i select any of them. they are duplicated. there are 2 windows, and when one is selected and goes into the next window, which seems to act like a "are you sure?" window, instead of the 3 options, there are  6. duplicates of each option. when select one, duplicate is also selected
not an issue as in a problem, but has occurred each time start a new user

**Comment by elfiyang16** [comment]
@Elmoutcault do you refer to here? Can you give a more detailed ill
![image](https://user-images.githubusercontent.com/29664811/85542090-a27c2b80-b610-11ea-9974-f14de91d40c9.png)
So from ux perspective, do you mean it would be less confusing if we just keep only one of the options to create roles: for example tick box on the left panel?
![image](https://user-images.githubusercontent.com/29664811/85542531-14ed0b80-b611-11ea-8540-da3e698dd063.png)

**Comment by Elmoutcault** [comment]
Oh no its not the roles and selected boxes that are duplicated. its that there's literally duplicates and when one is pressed they both are selected.  
![15929990667773109722890280425542](https://user-images.githubusercontent.com/63070858/85550098-78594800-b5d5-11ea-8142-2ed47266ee81.jpg)

One user i made i selected all and they both came up, duplicated
![15929992050848226117060662568461](https://user-images.githubusercontent.com/63070858/85550375-c1110100-b5d5-11ea-9bd6-21f694ab9480.jpg)

**Comment by Elmoutcault** [comment]
I believe the doubling occurs when pressing the arrow keys between the roles and selected box. Just got them to triple by pressing back and forth with those arrows, not always selecting all, and got some of the unchecked roles into the selected box, and since some boxes are blank, unchecked, its not letting me press save
![15929999952858164049054456139191](https://user-images.githubusercontent.com/63070858/85552233-a6d82280-b5d7-11ea-83f7-39621db7399c.jpg)

**Comment by dadiorchen** [comment]
![record](https://user-images.githubusercontent.com/5744708/85969504-6d018480-b9fa-11ea-802b-290deccc7530.gif)
@elfiyang16 I have called with Elm, see this video about how to reproduce this problem.

**Comment by Elmoutcault** [comment]
Very happy to say that the problem seems fixed and I cannot recreate the issue. Thank you so much @elfiyang16 and @dadiorchen for all the great work and for helping me with this issue!
