### ISSUE TITLE
Evertime approved/rejected trees, the list will refresh and reload those images.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#286]
![record](https://user-images.githubusercontent.com/5744708/85641655-d1060f00-b6c1-11ea-9fbc-389a0cf69938.gif)
This would slow down the operation of verifying.

**Comment by dadiorchen** [comment]
@nmcharlton can you take a look at this issue?

**Comment by dadiorchen** [comment]
@nmcharlton I have been worried about the verify pagination, I thought it's pretty tricky, so what's your anticipation about this issue?

**Comment by nmcharlton** [comment]
We currently replace all tree cards with placeholders when loading more trees, which is overkill.
In the case of verification, we are only loading a few more trees (often just one) to the end of the page, so can show the rest of the trees immediately and just have placeholders for the new trees.
I'll put together a fix now.
