### ISSUE TITLE
test.admin verify section not saving tags of different species

### ISSUE THREAD

**Issue by Elmoutcault** [Greenstand/treetracker-admin-api#288]
when on the verify page, if I put the name of a picture as "mango" and approve it, then look for that species. it isnt showing up.

**Comment by elfiyang16** [comment]
I will take a look

**Comment by elfiyang16** [comment]
Done -- created a foreign key on trees table referencing tree_species @Elmoutcault please try to test again
![image](https://user-images.githubusercontent.com/29664811/85720376-4684d600-b6e8-11ea-855a-09d01c78101f.png)

**Comment by Elmoutcault** [comment]
hey thank you! yes, that is showing up now. unsure tho, is the filter section supposed to be able to go through the verified pictures like, if i put down specifics on the filters and press the verify button nothing comes up. which makes sense. is this supposed to happen? I'm asking out of curiosity as well as wantingto know how to better test the system. thanks!

**Comment by ZavenArra** [comment]
do you mean the 'Apply' button?

**Comment by Elmoutcault** [comment]
@deepwinter yes. I meant the apply button. sorry about that

**Comment by elfiyang16** [comment]
Sorry I'm not sure if I get your question right @Elmoutcault - can you clarify what is the desired behaviour you expect to see when you use Filter with Species?

**Comment by Elmoutcault** [comment]
@elfiyang16  yes, sorry about that. I guess what I'm saying is that I'm confused with having the filter search on top as well as the tag section on right. testing everything that was an issue is now working smoothly! it's all doing what I think it is supposed to, but trying to figure how to test the top filter section. is there suggestions? as in, what would be best way to test the filters on this page

**Comment by elfiyang16** [comment]
@dadiorchen I'd assume there will be a user manual documenting the right way of doing stuff when release?E.g. how to run the filter correctly?

**Comment by dadiorchen** [comment]
@elfiyang16 no... we don't have it yet...
