### ISSUE TITLE
Reject section select fields not working

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#289]
When you mark a picture to reject you can only choose "Not a Tree" and the second radio select "Not an approved tree" the next five are not clickable.

**Comment by elfiyang16** [comment]
@sebastiangaertner do you get any console error when radio buttons are not clickable?
![image](https://user-images.githubusercontent.com/29664811/85708440-120b1d00-b6dc-11ea-84f3-dcf47875e044.png)

**Comment by dadiorchen** [comment]
@sebastiangaertner where did you do it? prod, test environment?

**Comment by dadiorchen** [comment]
Oh, @sebastiangaertner I got it, it was a bug existed in prod, we have solved it, take a try on the test env, you will find it's gone.

**Comment by dadiorchen** [comment]
@sebastiangaertner I will close it, please waiting for our next release, it will solve this.
