### ISSUE TITLE
Tree Image gallery for quick reviewing and disabling of fake tree entries.... 

### ISSUE THREAD

**Issue by gloriaLVela** [Greenstand/treetracker-admin-api#29]
Open
Tree Image gallery for quick reviewing and disabling of fake tree entries.... #32
sebastiangaertner opened this Issue on Jun 1, 2018 
  
Ready to be worked on in Tree-Tracker Admin

Tree Gallery

 @sebastiangaertner sebastiangaertner changed the title Tree Image gallery for quick reviewing (done by human for now) to make sure its actually a tree on the picture and not something else. Best would be a kind of Gallary with something that can disable the tree entry quickly. Tree Image gallery for quick reviewing and disabling of fake tree entries.... on Jun 1, 2018
@jparaujo
 Member
jparaujo commented on Jun 4, 2018
About my suggestion to use AI
https://greenstand.slack.com/archives/C8W6GT9MZ/p1528157040000043

 @jparaujo
 Member
jparaujo commented on Jun 6, 2018
After a quick discussion yesterday, we decided to make this feature available next in the Admin Panel. Something simple but functional for starters, to solve the current situation of "shoes pictures".

 @jparaujo jparaujo self-assigned this on Jun 6, 2018
 @jparaujo jparaujo added this to Backlog in Tree-Tracker Admin on Jun 6, 2018
 @jparaujo jparaujo moved this from Backlog to To do in Tree-Tracker Admin on Jun 6, 2018
 @jparaujo jparaujo moved this from To do to In progress in Tree-Tracker Admin on Jun 6, 2018
@thiagodemellobueno
 Member
thiagodemellobueno commented on Jun 7, 2018
@jparaujo - do you see tree images being broken out into their own api top level object, and then being simply associated with trees? this may make some things easier (less parsing when only the image matters)

 @jparaujo
 Member
jparaujo commented on Jun 7, 2018
@thiagodemellobueno I think we have only one photo at the tree level, so maybe a dedicated model on the front (I believe it would be like this anyway) and a URL bringing only imageUrl and id from the tree api would be enough. Unless by parsing you mean something else I'm not seeing here.

 @thiagodemellobueno
 Member
thiagodemellobueno commented on Jun 20, 2018
Possibly of use in these efforts: https://www.npmjs.com/package/react-masonry-component

 @thiagodemellobueno thiagodemellobueno added enhancement  Epic  labels on Jun 20, 2018
@jparaujo
 Member
jparaujo commented on Jun 20, 2018
That's a nice one. I'm currently experimenting with this: https://bvaughn.github.io/react-virtualized/#/components/Masonry

But having issues on auto positioning. I'm guessing it's something related with the Material theme we have in place. I will find out tonight. Haven't had much time to invest since our last meeting...

 @thiagodemellobueno
 Member
 thiagodemellobueno commented on Jun 20, 2018
 No worries, just doing a little garden tending.
…
 @sebastiangaertner
 Member Author
 sebastiangaertner commented on Jun 20, 2018
 Looks good. If even I understand the package code...
--
Sent from myMail for Android Wednesday, 20 June 2018, 02:49PM +01:00 from Thiago de Mello Bueno  notifications@github.com :
…
 @thiagodemellobueno thiagodemellobueno moved this from In progress to To do in Tree-Tracker Admin on Sep 25, 2018
@thiagodemellobueno
 Member
thiagodemellobueno commented on Sep 25, 2018 • 
I see a series of subtasks we can break out (@jparaujo probably has done some part of this already)

  Query trees with images
  Wire up checkbox selection (see tree table)
  Wire up buttons (disable and delete)
  Set up a masonry view with thumb
 @thiagodemellobueno thiagodemellobueno added the help wanted  label on Sep 25, 2018
 @thiagodemellobueno thiagodemellobueno added this to the Tree Gallery milestone on Sep 25, 2018
 @Davidezrajay Davidezrajay referenced this issue on Oct 17, 2018
 Open
Implement Next Tree Button #57
 @thiagodemellobueno thiagodemellobueno unassigned jparaujo on Nov 29, 2018

**Comment by ZavenArra** [comment]
This is partially complete and now tracked elsewhere.
