### ISSUE TITLE
'Palm' does not work as a Capture Approval Tag

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-api#299]
There are a couple of typos in the `capture_approval_tag` options in `TreeImageScrubber.js`:
```
<FormControlLabel 
  onClick={() => handleCaptureApprovalTag('plam')}
  value='plam' control={<Radio/>} label='Palm' />
```
The value is `plam` rejected by the database as not a valid type.
The valid types are:
```
simple_lead
complex_leaf
acacia_like
conifer
fruit
mangrove
palm
timber
```
Note that the typo in `simple_lead` is mirrored in the client, so this option is not rejected by the database:
```
<FormControlLabel
  onClick={() => handleCaptureApprovalTag('simple_lead')}
  value='simple_lead' control={<Radio/>} label='Simple leaf' />
```

**Comment by ericlvogt** [comment]
I can look into this for you.
