### ISSUE TITLE
A security loophole, about remember me. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#304]
If the user selected 'remember me', then token would be stored locally, so, if something of this account changed by administrator,  then the data in the token stored at the user's computer would be stale, but currently, we can not recognize it. 
We need:
* Force user to input password again if it changed.
* Disable user to login if active was set to false. 
* Update the user's role/permission if it changed.

**Comment by elfiyang16** [comment]
do we already have correspondent feature in point 2& 3 regarding active/inactive and permission?

**Comment by elfiyang16** [comment]
also is this a piece of work for test_release or master branch? @dadiorchen

**Comment by dadiorchen** [comment]
@elfiyang16 this has nothing to do with the active feature, it's about: when the user setting (like password, active) changed, we need to re-check the token:
* if password was changed, then disable the token, force user login again. 
* if active was disabled, force user logout.
* if role/permission was changed, then refresh the user roles stored in the token.

**Comment by elfiyang16** [comment]
Ok just to confirm if it's a change on the test_release or master branch @dadiorchen
