### ISSUE TITLE
Active status default to true

### ISSUE THREAD

**Issue by elfiyang16** [Greenstand/treetracker-admin-api#306]
when admin creates a user,set the active status defaults to true (aka newly created user will have a property active set to true)

**Comment by elfiyang16** [comment]
@dadiorchen i remember that I did something previously (not default to true but there's this visual element enable). Is it something not ready to release? In this case, in issue 304, I suggest not to include (Acitve = false) will force user log in manually again, as  most user active === undefined when this user is created.

**Comment by dadiorchen** [comment]
Really? But in my mind, this column (active) has a default value false, so it's impossible to get active === undefined? I thought.
