### ISSUE TITLE
Creating "rate" field in entity setting it to 3% standard rate by default 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#310]
The rate field in the entity will determine the percent of tokens charged by Greenstand for the transaction. This field can only be changed by customer care admins with approval of some form of higher authority level.

**Comment by elfiyang16** [comment]
Where is this token creation step happens in admin panel? Also what is the entity please? @sebastiangaertner

**Comment by elfiyang16** [comment]
Ah I saw the entity table in the db, but still confused about its usage 
![image](https://user-images.githubusercontent.com/29664811/91171910-3fbc1480-e6d3-11ea-820f-24408db457bf.png)

**Comment by nmcharlton** [comment]
This is out of scope for the Admin Panel and probably belongs in treetracker-database.
