### ISSUE TITLE
Trees page: 'Time created' filter does not work

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-api#316]
- When the _Time created_ fields in the Trees filter sidebar are left blank, `timeCreated` is still appended to the API query using today's date. It should be omitted.
- When valid dates are entered, the query string is incorrectly formatted, so no matches are found.

All of this means the filters never work in the Trees page.

Additionally, the date format should either be ISO standard (YYYY-MM-DD) or should use the locale of the user.
If US date format must be used, it needs to be explicit.

![Screenshot 2020-07-19 at 11 42 38](https://user-images.githubusercontent.com/5558838/87872944-064a0800-c9b5-11ea-8a97-09bd2401416c.png)

**Comment by dadiorchen** [comment]
@nmcharlton Sorry I'm not familiar with US date format, what does it look like? Did we use it somewhere?

**Comment by nmcharlton** [comment]
@dadiorchen US date format is MM/DD/YYYY, e.g. 07/20/2020 for today (or, more commonly, July 20, 2020).
We should use a consistent format (either international or using locale to determine the appropriate local format) across the project for displaying dates.

We currently use `m/d/yyyy` in the Trees table:
![Screenshot 2020-07-20 at 09 23 47](https://user-images.githubusercontent.com/5558838/87915960-baf23100-ca6a-11ea-8160-f2323d9ee14b.png)

**Comment by dadiorchen** [comment]
You are definitely correct!

**Comment by phips30** [comment]
We could use the locale from the browser to determine the users location, for example in Fireforx this works with navigator.languages command in the console. Afterwards, the date can be manipulated using date-fns (very lightweight and fast) or maybe also moment.js (very heavy -> larger bundle size).

**Comment by dadiorchen** [comment]
How about use momentJs, the reason is that we are already using it ...  @phips30 are you interested in taking this ticket?

**Comment by phips30** [comment]
Yes i will have a look into the filter issue and the formatting based on location.
One question, i only saw that moment.js is included in the package.json but I couldn´t find any usages.
The current date-utility package which is used in the application is date-io/date-fns, which is some sort of conglomerate including different date packages like moment.js, date-fns etc.

**Comment by nmcharlton** [comment]
@phips30 The native JS Date type supports [locale formatting](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString): `Date.toLocaleString()` with no parameters.

See also `Date.toLocaleDateString()`.

**Comment by nmcharlton** [comment]
This issue was fixed by @dadiorchen in commit ccedc67f9dc0605a3355d29807df4f0442c0c294 on the `test_release` branch, which has now been merged into `master`.
