### ISSUE TITLE
Using 'React-Router' to deal with the page navigation. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#318]
Currently, we just use React Context to handle page jumping, the menu changing, now with the project becomes bigger and bigger, 'React Router' turns out to be more and more desired for us. So let's use React Router to handle this project's page transition.

**Comment by elfiyang16** [comment]
I will take this

**Comment by dadiorchen** [comment]
:) @elfiyang16 I am glad you are interested in this, @nmcharlton have you started for this? Or let @elfiyang16 take it

**Comment by nmcharlton** [comment]
@dadiorchen I haven’t started this one.

@elfiyang16 It’s all yours 😄

**Comment by elfiyang16** [comment]
Thanks will push it soon.
