### ISSUE TITLE
Species management section

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#332]
The Species management should have its own section in the admin panel. Listing, adding, editing, deleting of species should be possible performed by special admins. A statistic view on what species is planted how often ideally by country would also be a great addition to the system.

**Comment by dadiorchen** [comment]
Maybe we also need to think about 'Merge and fix' function just like the planters? I noticed we got some species that look the same?

**Comment by dadiorchen** [comment]
I made a basic UX for this part, @sebastiangaertner do you have any suggestions on this? 
https://14bvv4.axshare.com/#g=1&p=species
![image](https://user-images.githubusercontent.com/5744708/89120752-56fc4d80-d4eb-11ea-9e3c-373f6c3f5610.png)

**Comment by sebastiangaertner** [comment]
Why was this closed?

**Comment by sebastiangaertner** [comment]
Yes a merge function is needed here.

**Comment by sebastiangaertner** [comment]
> Maybe we also need to think about 'Merge and fix' function just like the planters? I noticed we got some species that look the same?

Yes totally.

**Comment by dadiorchen** [comment]
@sebastiangaertner I have split this into several tickets to implement it, so I thought we can close this and assign people to solve these tickets?
![image](https://user-images.githubusercontent.com/5744708/90202625-c4c04780-de10-11ea-8272-03b08c8e2634.png)
