### ISSUE TITLE
Assigning selfie to planter

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#333]
In the list of planter once clicked on planter detail it should show up all selfie taken by that person. A simple select profile picture feature is needed to assign a good image to the planter which is then referenced in the actual planter table.

**Comment by dadiorchen** [comment]
@sebastiangaertner can you tell me where are those selfie photos in the DB? In the planter table, there is just a single field called: "image_url", so looks like only one picture there?

**Comment by Davidezrajay** [comment]
@dadiorchen the images come in on the trees table when the user signs in on the app. We than set the url manually. If the image is bad, or sideways, we download it, upload it and then get a new URL

**Comment by sebastiangaertner** [comment]
And that manual process is what i was pointing out to be manageable within the admin panel.

**Comment by nmcharlton** [comment]
@sebastiangaertner explains this feature [in this video](https://www.youtube.com/watch?v=ze6Khef8Zj0&t=00m30s)

**Comment by dadiorchen** [comment]
We can get the source of pictures for planters from table: planter_registration:
For the admin panel, we should have a place to let user choose selfie pictures from the source, and select one to become the photo of the planter.
And also admin user can upload a picture for this planter.
There should be a permission item for this, like: manage_planter_picutre, so we can assign some one to do this work on the admin panel, as an admin user.

**Comment by nmcharlton** [comment]
I'll get to work on a design for this.

**Comment by nmcharlton** [comment]
This feature will be part of an _Edit Planter_ dialog.
Roles with the `manage_planter` policy will see an edit icon in the planter detail drawer.

![image](https://user-images.githubusercontent.com/5558838/102827449-82b89b00-43da-11eb-9769-8db4d887f06f.png)
