### ISSUE TITLE
Tidy up wording/spelling on login screen

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-api#336]
A few minor corrections/suggestions for the text on the login screen.

### Login failure message
The login failure message currently states:

> Can not login, please check your username passowrd or contact the admin ...

It should read:

> Could not log in. Please check your username and password or contact the admin.

### LOGIN button
The

> LOGIN

button should be labelled

> LOG IN

(Please excuse the pedantry 😜 ) 

### Input labels

> userName
> password

should be

> Username
> Password

could be capitalised too.

**Comment by dadiorchen** [comment]
Hey, I need your correct on this, I hope I am more accurate in English expression!
