### ISSUE TITLE
Add species list into admin panel. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#338]
To add a new feature to the admin panel, the species management. As first step, add the species list:
* Add 'Species' menu item on the left.
* A Species list with pagination. 

https://14bvv4.axshare.com/#g=1&p=species&c=1
![image](https://user-images.githubusercontent.com/5744708/89232490-1ea75d00-d61a-11ea-8a84-4e1dc528b151.png)

**Comment by elfiyang16** [comment]
I'd like to take this but can we consolidate the test_release branch and master branch please? The menu list is very different for now, it doesn't seem the react-router is applied on master.   @dadiorchen .

**Comment by dadiorchen** [comment]
@elfiyang16 we are on master branch.

**Comment by elfiyang16** [comment]
Thanks I will take this then. Might need a bit time to implement
