### ISSUE TITLE
Species: edit current species item.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#339]
On the species list page, click 'edit' icon to edit the detail of a species. 

https://14bvv4.axshare.com/#g=1&p=species&c=1
<img width="968" alt="Screen Shot 2020-08-04 at 6 19 32 AM" src="https://user-images.githubusercontent.com/5744708/89232703-907fa680-d61a-11ea-85af-86f614977d1e.png">

**Comment by dadiorchen** [comment]
Need to check the name isn't the same with any other species in the DB.

**Comment by elfiyang16** [comment]
let me continue on this
