### ISSUE TITLE
To sort the species by some columns.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#340]
Should be able to sort the species by some column, they are:
* The ID
* The name.

<img width="968" alt="Screen Shot 2020-08-04 at 8 47 18 AM" src="https://user-images.githubusercontent.com/5744708/89240624-41903c00-d62f-11ea-918b-54abe5684907.png">

**Comment by elfiyang16** [comment]
happy to implement this, but i wonder what is the purpose of this ? sort by ID is totally understandable, but why do we want to sort by name (assuming alphabetically?) @dadiorchen

**Comment by dadiorchen** [comment]
I thought sorting by name is helpful when user wants to find some species, and easy to tell if there are some spell mistakes in the species name, sometimes people input the wrong name with tiny typo.

**Comment by dadiorchen** [comment]
By the way, please ignore the case/capital when sort, Mongo and mongo should be neighbors in the list.
