### ISSUE TITLE
Species: add new species.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#341]
Should be able to add new species. The dialog of this can be the same as the 'edit' function. 
https://14bvv4.axshare.com/#g=1&p=species&c=1
<img width="968" alt="Screen Shot 2020-08-04 at 8 50 34 AM" src="https://user-images.githubusercontent.com/5744708/89240744-9633b700-d62f-11ea-898e-7200b123c516.png">

**Comment by bsbjones27** [comment]
Hey, I will try this one out. Thanks.

**Comment by nmcharlton** [comment]
This should be consistent with the Edit Species dialog.

![Screenshot 2020-12-06 at 11 28 53](https://user-images.githubusercontent.com/5558838/101278873-3bb18f80-37b6-11eb-838c-96dd79ecadec.png)

**Comment by luacmartins** [comment]
@nmcharlton  I would like to attempt this one. Thanks!
