### ISSUE TITLE
Species, a column count the trees which were tagged with this species. 

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#343]
On the species list table, add a column called 'trees', and count the trees which were tagged as this species. 

https://14bvv4.axshare.com/#g=1&p=species&c=1
<img width="968" alt="Screen Shot 2020-08-04 at 8 58 32 AM" src="https://user-images.githubusercontent.com/5744708/89241258-f4ad6500-d630-11ea-8f32-038a8ae32493.png">

**Comment by elfiyang16** [comment]
I will do this
