### ISSUE TITLE
Clean the code, removing all the unused code for the client on the project

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#344]
We are blocked by the warning of unused variables on the client now, need someone to remove all of them to let us pass the CI on the Github Action!
```
./src/components/TreeDetails.js
32
  Line 1:17:  'Component' is defined but never used                                                                      no-unused-vars
33
  Line 2:8:   'PropTypes' is defined but never used                                                                      no-unused-vars
```

**Comment by jun383914** [comment]
I will take this one.

**Comment by nmcharlton** [comment]
@jun383914 has removed all unused dependencies.

We now need someone to decide whether the unused variables and sections of code can be safely removed too.
