### ISSUE TITLE
Menu Enlarge Link Target Box

### ISSUE THREAD

**Issue by ericlvogt** [Greenstand/treetracker-admin-api#350]
Currently, the target box to route a user to a separate page is on the menu text only (red box). Update so the entire menu item links to the page (green box).
![gsmenu](https://user-images.githubusercontent.com/63984391/89721557-36753d00-d99c-11ea-974c-fe4ff20c3a23.png)

**Comment by dadiorchen** [comment]
Yes, that makes sense!

**Comment by elfiyang16** [comment]
Can we confirm which branch is for this issue?
On current master the layout is very different and has no route @ericlvogt 
![image](https://user-images.githubusercontent.com/29664811/89819455-67dc3d00-db43-11ea-8ee0-debd67358eb9.png)

**Comment by ericlvogt** [comment]
@elfiyang16 this is for the test_release branch. Seemed to result from the addition of react router.

**Comment by elfiyang16** [comment]
I see. Thanks for confirming!

**Comment by dadiorchen** [comment]
@ericlvogt let's switch to the master branch, the code of test_release is stale...

**Comment by ericlvogt** [comment]
@dadiorchen thanks for letting me know I'll move over to the master now. The test_release react router code seems to now be merged into the master branch so this issue is valid once more.

**Comment by nmcharlton** [comment]
Resolved in #372
