### ISSUE TITLE
Display total number of trees to be verified

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#358]
When logging in the admin panel the dashboard should point out how many trees have to be processed. 

To be displayed after user logs in to the admin panel. 

- ~to be verified~ "Pending"

These numbers should:
- represent the total number of trees that are accessible to that specific admin panel user
- represent the total number of trees that do not have any tags attached to them (entirely unprocessed) 

A later iteration will have 'nice to have' statistics:
- total number of trees
- verified trees 
- number of countries
- number of users
- etc.

**Comment by BirdTho** [comment]
I'll take this one.

**Comment by BirdTho** [comment]
@sebastiangaertner Where am I to find the countries?
Also, how many users, the admin-users table or a different table?

**Comment by BirdTho** [comment]
Only reference to tag I see is captureApprovalTag in the trees table

**Comment by sebastiangaertner** [comment]
The countries you would find through region tables i believe or tree_region. I do not have access to the data so i can not know for sure. They are determined by predefined layers that are polygons from international country border data.

Assuming that the "verified" column has that purpose it would need to be set to true once a tree has been processed through the admin panel either with "approved" true or false. Dadiorchen is this logically correct. I believe the verified column does not change at this point. It should be set to true on any admin panel process.

**Comment by sebastiangaertner** [comment]
Amount of users would be total number in "planter" table

**Comment by BirdTho** [comment]
#363 
Pull request submitted, have responded to PR comments

**Comment by BirdTho** [comment]
Wooo 1st PR
