### ISSUE TITLE
Display appropriate message when login failed

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#368]
If user login admin panel with the username which does not exist in the DB, should display message like: "the user name 'xxx' does not exist"
Now, the message is not so clear, and the server response 500 rather than 401. Also maybe we should consider the response spec to let the client know what happened on the server?
<img width="1438" alt="Screen Shot 2020-08-26 at 4 05 58 PM" src="https://user-images.githubusercontent.com/5744708/91278304-a108e400-e7b6-11ea-930f-77a18a0b3c65.png">

**Comment by alansvits** [comment]
I am trying fix it. Intermediate result like this:
![noexistuser](https://user-images.githubusercontent.com/15067440/92134762-98e22180-ee12-11ea-8953-b74ed843c4da.png)
