### ISSUE TITLE
Bug in account page

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#369]
<img width="1438" alt="Screen Shot 2020-08-26 at 8 19 12 PM" src="https://user-images.githubusercontent.com/5744708/91302722-7f6d2400-e7d9-11ea-9a28-4e3c40238c64.png">
Seems like there are some bug in this page, the role list would display repeated list in some way.

**Comment by elfiyang16** [comment]
Is there role display now already? I still see the page below. Is it on master branch? @dadiorchen 
![image](https://user-images.githubusercontent.com/29664811/91441181-ab36eb00-e867-11ea-8a73-19622b3308d2.png)

**Comment by alansvits** [comment]
I think I fixed it. I checked only with admin user role changing.
