### ISSUE TITLE
Hide "Note" on Verify side panel until functionality is implemented

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-api#371]
Currently, the text box marked "Note (optional)" on the side panel of the Verify page is not hooked up, giving users a false perception that notes are being saved somewhere.

There has been discussion about how this field should be handled in relation to a similar field completed by planters on the Treetracker app, but until something is decided, this field should be hidden to avoid confusion.

![Note](https://user-images.githubusercontent.com/5558838/91704702-de34f380-eb73-11ea-9d04-cf6d8554998e.png)

**Comment by alansvits** [comment]
I comment out that piece of code. Is it a normal solution?
![Screenshot 2020-09-03 at 13 54 42](https://user-images.githubusercontent.com/15067440/92106480-20b53500-eded-11ea-94ea-a9be99e57224.png)

**Comment by nmcharlton** [comment]
@alansvits Commenting out code is ok, but often leads to confusion later on, or code gets deleted when someone tidies up.

It might be better to add `false &&` to the front of the React component to prevent it being rendered, but with minimal overhead, e.g.
```
{false && <Grid className={`${classes.sidePanelItem}`}>
  <TextField placeholder='Note (optional)' ></TextField>
</Grid>}
```

This makes it explicit to any other developers that the code is deliberately being skipped.
You could also add a comment to explain the reason.

**Comment by alansvits** [comment]
@nmcharlton You are right! That looks much cleaner.
