### ISSUE TITLE
Clean up the code for the server project. 

### ISSUE THREAD

**Issue by ghost** [Greenstand/treetracker-admin-api#389]
When I do linting for the server project, I get multiple linting issues. It may be helpful to configure TSLint and automatically fix the the TSLint warnings.

**Comment by BirdTho** [comment]
I'd like to work on this.

**Comment by BirdTho** [comment]
@nmcharlton Could you assign this to me (or allow me?)

**Comment by BirdTho** [comment]
Associated PR #392

**Comment by BirdTho** [comment]
I think this is ready to be looked at, tested, closed. The dev work is done, lest and request for changes comes through.
