### ISSUE TITLE
Planter registration date needs to be shown

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#390]
We need to add the registration data of a user and ideally see if a planter has been onboarded.  For now a date in the user list would be great. 

![Screenshot 2020-10-02 at 16 18 31](https://user-images.githubusercontent.com/5558838/94940089-ed88c300-04ca-11eb-9058-dbc8379c37c2.png)

Is Person ID already linked?

**Comment by nmcharlton** [comment]
Person ID does appear to be linked, but I haven't seen it populated in the DB.

**Comment by nmcharlton** [comment]
Related to #423
