### ISSUE TITLE
'Disabled' menu items can still be selected

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-api#402]
Where pages have either not been been implemented yet or users do not have permission to access a page, the menu item appears disabled.

Currently, the link is not disabled on these items, so the user can click through anyway:

![Screen Recording 2020-09-20 at 11 05 18](https://user-images.githubusercontent.com/5558838/93708921-093ab380-fb32-11ea-8a68-5ab0c5668e47.gif)

**Comment by BirdTho** [comment]
I'd like to take this one.

**Comment by BirdTho** [comment]
See PR #407
