### ISSUE TITLE
System user roles getting repeatedly listed 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#417]
![Screenshot 2020-09-27 at 21 00 29](https://user-images.githubusercontent.com/3283800/94523694-dd09eb80-0231-11eb-8e49-93dae699f7fc.png)

**Comment by nmcharlton** [comment]
Duplicate of #369

**Comment by nmcharlton** [comment]
This is fixed on the `master` branch but has not yet been merged into `test_release` and deployed.

**Comment by nmcharlton** [comment]
Fixed released (#463)
