### ISSUE TITLE
Can not delete admin panel user

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#418]
When you select a user you can not delete the user.
Related issue is that the password change does not work. #419

**Comment by Davidezrajay** [comment]
https://github.com/Greenstand/treetracker-admin/issues/430

**Comment by nmcharlton** [comment]
This may be caused by the same constraints that are causing #432.
The `DELETE` operation is not allowed on the production database for the Admin Panel API user, so a different strategy is required.

**Comment by nmcharlton** [comment]
Correction: The delete user button is not hooked up in the version of the Admin Panel in test/prod.
My previous comment still holds though.
