### ISSUE TITLE
Show 'Note' in tree capture information in tree detail dialog (Verify page)

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-api#426]
The tree record includes a `note` field, optionally populated by the planter at the time of capture.
This should be displayed to the user on the tree detail dialog on the Verify page.

![Screenshot 2020-10-02 at 16 30 28](https://user-images.githubusercontent.com/5558838/94941297-95eb5700-04cc-11eb-8e3c-b40eda8adace.png)

**Comment by luacmartins** [comment]
@nmcharlton I would like to work on this issue.
