### ISSUE TITLE
Add `none` to species search window

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-admin-api#428]
This search box is awesome and has pushed us so far forward! 

Add the ability to see which trees have not been tagged. There is the counter to the `all` feature. The default should be a `none` or `not tagged`. 

This gives the use the ability to see all the trees that have no species attached to them.

![Screenshot (151)](https://user-images.githubusercontent.com/25363572/95027749-6745bb80-0647-11eb-8bde-eb7f50b41d09.png)

**Comment by nmcharlton** [comment]
I'll grab this one 😄
