### ISSUE TITLE
Improve the UX on adding new admin user

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#431]
When adding user, after clicking the 'save' button, if the operation is slow, it's better we DISABLE the button and display some spin animation to indicate that processing is going on.

![image](https://user-images.githubusercontent.com/5744708/95934589-d075bd80-0e03-11eb-8b93-c6f205e90e60.png)

**Comment by nmcharlton** [comment]
Fix merged into `master` under #452
