### ISSUE TITLE
Fix security issues reported by github/npm

### ISSUE THREAD

**Issue by thiagodemellobueno** [Greenstand/treetracker-admin-api#44]

**Comment by ZavenArra** [comment]
Two places to look:

1) Run 'npm install' in client and server subdirectories, see vulnerabilities listed.
2) See https://github.com/Greenstand/treetracker-admin/network/alerts

**Comment by achock** [comment]
So I am getting the following warning signs:
#This is on client folder
> fsevents@1.2.7 install /Users/me/React/treetracker-admin/client/node_modules/chokidar/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 

#None on server
➜  server git:(master) ✗ npm install
added 558 packages in 8.021s

**Comment by ZavenArra** [comment]
That's interesting. 

@misterinterrupt  Is it possible that last round of npm audit we did fixed the modules, but that the setup of node of my personal laptop still have old global packages or something.

@misterinterrupt does npm i show audit warnings on your computer?

@achock Can you also look into the issues reported by github itself ? image below..

![image](https://user-images.githubusercontent.com/364622/56048730-18e78300-5d16-11e9-8d9a-34d80e80e228.png)

**Comment by achock** [comment]
@deepwinter 
I am getting a 404 on this link.
https://github.com/Greenstand/treetracker-admin/network/alerts

**Comment by ZavenArra** [comment]
@achock I invited you to Greenstand, but I'm not sure you accepted yet.  You probably don't have access to the link, that's why I pasted the image above in my previous message.

**Comment by misterinterrupt** [comment]
```
 (master):~/PROJECTS/treetracker-admin$ cd client/
 (master):~/PROJECTS/treetracker-admin/client$ npm i
npm WARN enzyme-adapter-react-16@1.1.1 requires a peer of enzyme@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ts-pnp@1.0.1 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

removed 6 packages, updated 1 package and audited 49002 packages in 8.878s
found 72 vulnerabilities (63 low, 9 high)
  run `npm audit fix` to fix them, or `npm audit` for details



(master)$ npm audit fix
npm WARN enzyme-adapter-react-16@1.1.1 requires a peer of enzyme@^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ts-pnp@1.0.1 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/react-scripts/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

up to date in 7.979s
fixed 4 of 72 vulnerabilities in 49002 scanned packages
  68 vulnerabilities required manual review and could not be updated

```

**Comment by misterinterrupt** [comment]
the warnings are coming from packages that are not updated by their maintainers to fix their dependencies yet, you can see what is not up to date, by running  `npm outdated`
we could try beta versions, but I don't think it is super important right now. 

once certain pkgs are on their next version like say.. 
react-scripts
latest: 2.1.8              next: 3.0.0-next.b0cbf2ca  

then we will likely see those warnings go down in number.

on this topic, if anyone is dying to do npm fun stuff, one could move the dev dependencies into the dev dependencies category in the package.json..    

but otherwise, leave it

**Comment by ZavenArra** [comment]
I think separating the dev dependencies is worth doing, it's a best practice.
