### ISSUE TITLE
Need to create filter for organization id in verification panel ASAP

### ISSUE THREAD

**Issue by JonTrimarco** [Greenstand/treetracker-admin-api#441]
![image](https://user-images.githubusercontent.com/59079365/97846690-6e6ff000-1cff-11eb-8091-09a85ba51ac8.png)

We need to create a filter for organization_id (planter.organization_id = filter value) in the Verify page of the admin panel. This would allow us to verify all of the trees taken by users of a particular organization. This is a critical function for several of our partner orgs.

This would probably require a join planter.id=trees.planter_id

**Comment by dadiorchen** [comment]
This is more complicated than what you described, we need to go through a whole entity tree

**Comment by dadiorchen** [comment]
Let's discuss this on issue #442

**Comment by nmcharlton** [comment]
Initial version delivered in #482
