### ISSUE TITLE
Easy way to exclude organizations trees from main admin panel account

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#442]
We as Greenstand need to be able to log in and by default hide the captures that come in from organisations that have their own login for verification. At the moment we (Greenstand) see the Freetown trees, OTP, Fairtree and other org trees which should only be visible by including them in the filter. That way we do not accidentally verify trees that are from other orgs. 

spec in progress from @deepwinter 
We are going to implement this as a default exclude filter based on entities (or just top level parent entities) that are in the entity relationship table. and will want to (eventually) have a UI to set this up. the default exclude filter should be per-user, persistant, and also be able to be disabled.

**Comment by dadiorchen** [comment]
This is a bit complicated, by default, org trees are hidden, then do you need to check those trees at some special case? need to show them out? 

I am considering if we can use a filter to do this. And by default, set the filter to hide of org trees.

**Comment by dadiorchen** [comment]
To filter by org, the logic is to find all the planter on the org-subplanters hierarchy tree.

**Comment by dadiorchen** [comment]
@deepwinter do you think it is okay to add an org filter in the tree verify?

**Comment by ZavenArra** [comment]
We are going to implement this as a default exclude filter based on entities (or just top level parent entities) that are in the entity relationship table. and will want to (eventually) have a UI to set this up.  the default exclude filter should be per-user, persistant, and also be able to be disabled.

**Comment by sebastiangaertner** [comment]
Its becoming almost impossible to work with the admin panel . There are 45000 trees from Freetown that they are late processing so we can not pick up the new ones from individual planters and smaller orgs...
