### ISSUE TITLE
Feature: remove useless species.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#444]
Should be able to remove wrong or useless species. 

In the DB, should set active to false to remove them, rather than delete the recode from DB.

**Comment by nmcharlton** [comment]
We should only allow the user to remove species with no trees allocated.
We'll need to set `active` on all the existing species to `true` when we roll this out.

**Comment by nmcharlton** [comment]
This issue depends on Greenstand/treetracker-database#63

**Comment by nmcharlton** [comment]
Duplicate of #486
