### ISSUE TITLE
Show Device info on planter detail

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#458]
We should pull in the device info through "devices JOIN planter_registrations ON
devices.android_id = planter_registrations.device_identifier" and display it on the planter information page.

**Comment by ZavenArra** [comment]
We want to show all devices for a planter right?

We will need to join planter_registrations to planter, and then to devices.

**Comment by gwynndp** [comment]
Do we collect the userAgent info when a user registers?  Do we assign the device identifiers or just take them directly from the devices? 

It looks like iOS and Android have different methodologies for creating their device ids.  If we take the ids directly from the devices, do we know we can use those device identifiers to tell if it came from iOS or Android?

https://searchcio.techtarget.com/definition/device-ID-device-identification

**Comment by AlexCornforth** [comment]
If you need any client side changes to make this easier I'm happy to help.
