### ISSUE TITLE
Formatting / Lint

### ISSUE THREAD

**Issue by thiagodemellobueno** [Greenstand/treetracker-admin-api#48]
I'm not a fan of airBNB but have used their lint styleguide as formatting enforcement in the past, and though there are some rules that annoy me / seem arbitrary, it's a good starting point.

https://github.com/airbnb/javascript/tree/master/react

**Comment by dadiorchen** [comment]
@Davidezrajay we have defined a simple code style guide in the readme, so I think could close this one, and if anyone has guide suggestions, let's discuss and append to the current guide if need.

**Comment by Davidezrajay** [comment]
@dadiorchen Super awesome. Thanks!
