### ISSUE TITLE
Can not delete species.

### ISSUE THREAD

**Issue by dadiorchen** [Greenstand/treetracker-admin-api#486]
Reproduce: 

1. Open test.admin.treetracker.org 
2. Go to the species page
3. Find one species which's tagged count is zero.
4. Click 'delete', click 'confirm'
5. Doesn't work.

The request is complaining `500` error:

<img width="1552" alt="Screen Shot 2021-01-04 at 3 51 08 PM" src="https://user-images.githubusercontent.com/5744708/103513212-1becb480-4ea5-11eb-8009-e1e069ef7273.png">

**Comment by nmcharlton** [comment]
Likely duplicate of #444

**Comment by luacmartins** [comment]
This functionality seems to be working in my local environment, but not on test.admin.treetracker.org as mentioned. What are the differences between both environments?

**Comment by nmcharlton** [comment]
> This functionality seems to be working in my local environment, but not on test.admin.treetracker.org as mentioned. What are the differences between both environments?

@luacmartins The DB policy in test and production prohibits `delete` instructions. Instead, we have an `active` column in all tables that is used to mark items as deleted. The front end should never show anything that is inactive.

See #444

**Comment by nmcharlton** [comment]
This issue depends on Greenstand/treetracker-database#63

**Comment by nmcharlton** [comment]
Fixed in #530
