### ISSUE TITLE
Filter by "not tagged"

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#489]
We need to be able to filter out the tagged trees (trees without species or custom tags). 
Use case: finding untagged trees in the system and give them at least one tag such as species or other tags. 
It will be two separate controls. (species and tags)

**Comment by nmcharlton** [comment]
This functionality exists in the Verify tool filter for Species (_Not set_).
A similar option could be added to the Tag dropdown.

![Screenshot 2021-01-17 at 22 50 13](https://user-images.githubusercontent.com/5558838/104858374-7e6a9980-5916-11eb-86f4-9fe50c0261ed.png)

**Comment by luacmartins** [comment]
@nmcharlton I would like to try this.
How can I go about uploading tagged trees to the dev db so I can test this feature in dev (currently all trees in the dev db are untagged)?

**Comment by nmcharlton** [comment]
@luacmartins You can add tags to an existing tree from the Verify page by selecting it, populating the _Additional tags_ field and clicking _Approve_.

You'll need to change the _Approved_ filter to _All_ or _true_ to show it once it's been approved.
