### ISSUE TITLE
Organization trees are not included in the Audit Log

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-api#491]
Our audit log middleware intercepts API requests and logs the details of a request if its URL matches certain regexes.

https://github.com/Greenstand/treetracker-admin/blob/master/server/src/js/Audit.js#L93
```javascript
    } else if (/.*\/api\/trees\/\d+/.test(url)) {
```
This currently catches patches on `/api/trees/` but misses patches on trees associated with organizations (`/api/organization/{org_id}/trees/`).

It should catch all tree patches.

**Comment by luacmartins** [comment]
@nmcharlton I would like to attempt this issue!
