### ISSUE TITLE
Emit event on verification

### ISSUE THREAD

**Issue by arunbakt** [Greenstand/treetracker-admin-api#498]
This change is part of the [domain model migration project](https://github.com/Greenstand/system-design-docs/blob/master/domain-migration/project_plan.md). 

Summary: Emit a event and send it to message queue (RabbitMQ) when a tree capture is verified.

Details: When admin panel user takes an action to verify the tree capture, it is marked as verified along with tags, age and other attributes. In addition to these actions, an event indicating the action should be emitted to a queue in RabbitMQ. The event should contain the following info:

`id`: uuid of the tree capture,
`type`: The name of the event (useful and acts as a type classifier - in processing the events),
`verified`: boolean value that indicates if a tree capture is verified or not
`created_at`: datetime at which the event was generated
 
A sample event payload where a tree capture is verified is given below:
`{
"id": "eb8185b4-774f-492e-9f94-11f7d13f8154",
"type": "VerifyCaptureProcessed",
"verified": true,
"created_at": "2021-02-05T18:53:03.559Z"
}`

The events generated should be stored in a table (partitioned preferably)  so that in the event that message queue is down, the application continues to store the events to be replayed to the queue when messaging system is back online.

Please ping in development channel or in infrastructure channel in slack to request the dev connection string for the RabbitMQ messaging instance.

Use the following exchange and queue name for the publishing of the messages `admin-verifications` and `field-data:verifications`.

Note:
To give the implementer the context, the messages generated are to be consumed by [field data service](https://github.com/Greenstand/treetracker-field-data) to mark its capture data as processed for the sake of data integrity during the domain migration process.

**Comment by dadiorchen** [comment]
@arunbakt do we have any lib for this? Like a queue lib?

**Comment by arunbakt** [comment]
@dadiorchen I used `rascal` lib to publish events in field-data service. You can see the setup in the field data service [files](https://github.com/Greenstand/treetracker-field-data/tree/master/server/infra/messaging)
