### ISSUE TITLE
UI Style Guide & Wireframes

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-api#51]
Generate wireframes and a style guide that explains how the overall admin panel UI should function.  This should solve our questions from a UI/UX perspective, but leave more traditional 'design styling' (fonts and graphics) to a different responsibility.

**Comment by thiagodemellobueno** [comment]
@deepwinter - please elaborate on what you mean by
" but leave more traditional 'design styling' (fonts and graphics) to a different responsibility."

**Comment by rgesulfo** [comment]
Hi there- just curious, do we have mocks around the admin panel? Thanks

**Comment by ZavenArra** [comment]
@rgesulfo No, we do not.  It's something we need, and could make one of the targets for our June hackathon.

**Comment by rgesulfo** [comment]
@deepwinter Can we close this issue?
