### ISSUE TITLE
unable to delete species

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#553]
not possible to delete species that have 0 count.

**Comment by nmcharlton** [comment]
It looks like the `DELETE` is blocked by CORS.
I don't think we need to block `DELETE` in this way; the server decides what to do with a delete request (set `active=false`).

**Comment by nmcharlton** [comment]
Here's where it's set in the `development` environment.
We'll need to update `test` and `production` as well.
https://github.com/Greenstand/treetracker-admin-api/blob/06434372cb601d66f6c4692a2a2ad658ee252d0e/deployment/overlays/development/treetracker-admin-api-mapping.yaml#L8
