### ISSUE TITLE
Organization ID cannot be set to null in Planter

### ISSUE THREAD

**Issue by nmcharlton** [Greenstand/treetracker-admin-api#556]
Greenstand/treetracker-admin-client#71 aims to allow the user to set a planter's organization ID to `null`, but the current `planter` LoopBack model does not fully allow `null`:

```
  @property({
    type: Number,
    required: false,
    scale: 0,
    postgresql: {
      columnName: 'organization_id',
      dataType: 'integer',
      dataLength: null,
      dataPrecision: null,
      dataScale: 0,
      nullable: 'YES',
    },
  })
  organizationId?: Number;
```

According to https://github.com/strongloop/loopback-next/issues/2220#issuecomment-524567458, adding the following to the `@property` decorator fixes the problem:
```
jsonSchema: {
  nullable: true,
},
```

**Comment by nmcharlton** [comment]
@tranquanghuy0801 Here's the supporting API issue.

**Comment by tranquanghuy0801** [comment]
@nmcharlton  check my PR #557. Changing this allowed the null value of organizationId in the client
