### ISSUE TITLE
Org login dashboard numbers not correct

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#563]
See attached. This is showing for user THTP
![Screenshot 2021-05-19 at 17 54 07](https://user-images.githubusercontent.com/3283800/118836223-598a3100-b8cc-11eb-8b61-aae961de8157.png)

**Comment by nmcharlton** [comment]
This is a duplicate of Greenstand/treetracker-admin-client#86

**Comment by nmcharlton** [comment]
Fixed in Greenstand/treetracker-admin-client#107
