### ISSUE TITLE
Link to trees on webmap

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-api#66]
Create a link using the tree id to open our webmap in a separate tab and show the location of the tree.

The URL to show a tree by id on the webmap is http://{base_domain}/?treeid={tree_id}

For instance, in production this is:
https://treetracker.org/?treeid=1000

A quick fix for a basic operational need - there is no official UI spec for this at the moment.  For a now, a link in both the images and trees area would be ideal.  The text of the link should be **'Location.'**  It's fine to just it in where it seems to make the most sense for the moment.  We will be returning to this soon with a more clear UI spec, but it will take a while to push that out, and we need some of these features for operational reasons ASAP.

**Comment by sebastiangaertner** [comment]
This is an easy one or? It would be very helpful to have.

**Comment by sjaymoon15** [comment]
In which component/page do we want this link to be located? @deepwinter @Davidezrajay

**Comment by Davidezrajay** [comment]
![Screenshot (67)](https://user-images.githubusercontent.com/25363572/71298240-a82c4800-2333-11ea-8e28-80018889237b.png)

https://drive.google.com/a/greenstand.org/file/d/1QHSbjDL6E_X5ykFvwYGf6lG0KnSAJjfz/view?usp=sharing

**Comment by sjaymoon15** [comment]
PR #122 for the issue has been merged to master. This issue is probably good to be closed now.

**Comment by Davidezrajay** [comment]
@sjaymoon15 Thank you!!!
