### ISSUE TITLE
Add google analytics to Admin Panel

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#71]
below the google admin panel tracking ID and code

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-1280531-65"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-1280531-65');
</script>

**Comment by rgesulfo** [comment]
@sebastiangaertner Could you add me as contributor please? maybe for all Greenstand projects? Thanks
