### ISSUE TITLE
Finalize UI and look and feel for admin panel v1.1

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-api#72]
Current look and feel for v1.1 is the following:
![image](https://user-images.githubusercontent.com/364622/59728086-6c31f200-91ed-11e9-8c01-a4b5a0ac6c15.png)

However, new work has provided functionality for our data tables as:

![image](https://user-images.githubusercontent.com/364622/59728107-7eac2b80-91ed-11e9-8088-d38e18e08c3a.png)
![image](https://user-images.githubusercontent.com/364622/59728111-84a20c80-91ed-11e9-8b73-8836ac1924a4.png)

this ticket tracks the merging of these two UIs into a final spec for v1.1

**Comment by rgesulfo** [comment]
@deepwinter What's the delta? Just Updated datetime? Do you want me to add to the UI?

**Comment by ZavenArra** [comment]
The main thing I'm looking at is the way filters are shown and the other options there. One is pretty nice too - the show/hide columns functionality.

**Comment by ZavenArra** [comment]
We'll also need details on what the 'Search' and tree count controls in your spec are meant to do
![image](https://user-images.githubusercontent.com/364622/59729723-9a670000-91f4-11e9-8f2b-6f5ddaf85436.png)

**Comment by rgesulfo** [comment]
@deepwinter 
Here is the updated designs: https://sketch.cloud/s/Gzp55
I basically kept the columns settings, but different icons (which could potentially host more options) and the csv download. 
The printing feature is kind of an anathema for a project planting trees so I removed it ;)

To answer your 2 other questions:
1. "2,000" trees is the total number of trees "selected" (it depends on filters applied and search term)
2. The search box can work like the current implementation. Just a different UI.

Let me know if this good to go on your side. Thanks

**Comment by rgesulfo** [comment]
@deepwinter Are we good on this issue or do you need more from me?

**Comment by ZavenArra** [comment]
There are probably some small changes during implementation, but I think we are good.  Can you pull screens out of sketchpad relevant to the admin panel and place them in a folder in our gDrive?   Then we can close this out.

**Comment by rgesulfo** [comment]
Makes sense. Here is the G Drive link: https://drive.google.com/drive/u/0/folders/1uCXFLWnWhvHZs3JFyYKlmcBGg33txguu
