### ISSUE TITLE
Implement filtering using loopback

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-api#75]
Extend the API calls made to loopback to support the following filters.  These filters can be composed together.  Loopback supports all API calls for these filters using its where filter https://loopback.io/doc/en/lb2/Where-filter.html

Loopback API currently available can be viewed here:  http://localhost:3002/explorer/#/Tree

API calls should be implemented in models/trees.js following the current pattern of other calls, or improvements can be suggested.

Filters to implement:
Filter trees by tree id
```
curl --globoff  -X GET "http://localhost:3000/trees?filter[offset]=0&filter[limit]=200&filter[where][id]=115"
```

Filter trees by status
```
curl --globoff  -X GET "http://localhost:3000/trees?filter[offset]=0&filter[limit]=200&filter[where][status]=planted"
```
Filter trees by date created (date range, or before/after only)
```
Syntax for trrees after a date:
curl --globoff  -X GET "http://localhost:3000/trees?filter[offset]=0&filter[limit]=200&filter[where][timeCreated][gte]=2018-08-08"

Syntax for trees before a date:
curl --globoff  -X GET "http://localhost:3000/trees?filter[offset]=0&filter[limit]=200&filter[where][timeCreated][lte]=2018-08-08"

Syntax for trees between two dates:
curl --globoff  -X GET "http://localhost:3000/trees?filter[offset]=0&filter[limit]=200&filter[where][timeCreated][between]=2018-08-07&filter[where][timeCreated][between]=2018-10-01"

```

**Comment by ZavenArra** [comment]
![image](https://user-images.githubusercontent.com/364622/59982383-4d08db00-95c6-11e9-94ad-f1df507e396f.png)
![image](https://user-images.githubusercontent.com/364622/59982384-53975280-95c6-11e9-81d7-3f176175d09b.png)

**Comment by ZavenArra** [comment]
![image](https://user-images.githubusercontent.com/364622/59982389-66aa2280-95c6-11e9-84c3-e277cb5c3d0a.png)

**Comment by deepwinter** [comment]
These filters do not require additional work in loopback.  Use API explorer to get the appropriate where clauses using default loopback query specification.
