### ISSUE TITLE
Implement API endpoints for filtering trees by user

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-api#77]
Filter trees to show those associated to an email address or phone number (via the users table).

First get the user id from users API, then query for active trees.  curls below specify the query parameters to use.

curl for getting user id, these are the GET params to use:

```
curl --globoff  -X GET "http://localhost:3000/users?filter[offset]=0&filter[limit]=200&filter[where][phone]=3133333232 " -H "accept: application/json"
curl --globoff  -X GET "http://localhost:3000/users?filter[offset]=0&filter[limit]=200&filter[where][email]=matt%40asdf.com" -H "accept: application/json"
```
note URL encoding of @ in email address

returned object will be an array, object(s) in that array will contain a field 'id' which is the user id, and can be used to query trees as seen in the following curl:

```
curl --globoff  -X GET "http://localhost:3000/trees?filter[offset]=0&filter[limit]=200&filter[where][userId]=5&filer[where][active]=true"
```

**Comment by Davidezrajay** [comment]
thanks
