### ISSUE TITLE
Implement API endpoints for filtering trees by lat/lng and radius

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-api#78]
We need to filter trees in both table and image lists by lat/lng and a radius.  We use the postGIS extension in postgres server side for spatial queries.  Some research will need to be done to understand the correct pattern for implementing this query in our loopback driven API.  https://loopback.io/.  We are currently running loopback 4.0

This feature requires some advanced customization of loopback.  We need an engineer with specific LoopBack 4 experience in order to include this in our milestone.

**Comment by blancoal** [comment]
doing some research. 

[This](https://groups.google.com/forum/#!topic/loopbackjs/D0WCPIfHhR8) talks about making a geojson a property, but not quite what we want.

Have to map to something like this:
search lat/lon => searchPoint, searchRadius

SELECT tree
FROM trees
WHERE [ST_Distance](https://postgis.net/docs/ST_Distance.html)(searchPoint.geom, tree.geom) <= searchRadius

**Comment by blancoal** [comment]
I have made significant progress on this. @deepwinter has helped me on Slack.  I am using using the execute method and sending "SELECT * FROM Trees WHERE ST_DWithin(ST_MakePoint(lat,lon), ST_MakePoint(centerLat, centerLon), radius)",

**Comment by Davidezrajay** [comment]
Latlonsearch #106 Thank you @blancoal Super awesome to have this one!
