### ISSUE TITLE
Implement tree details view

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-api#79]
![image](https://user-images.githubusercontent.com/364622/59731121-d18be000-91f9-11e9-92a3-6b7c3d973cb0.png)
![image](https://user-images.githubusercontent.com/364622/59731133-d8b2ee00-91f9-11e9-8ae0-b00b05f019c3.png)
![image](https://user-images.githubusercontent.com/364622/59731172-f97b4380-91f9-11e9-8b4a-f17dcf2b3662.png)

Also see 
https://sketch.cloud/s/Gzp55/a/g4x03M

Total due and Donor information will not currently be visualized, as we do not have these features ready, but the interface for these features should be built as part of this ticket.

**Comment by Davidezrajay** [comment]
I'm going to close this as it will change on the new designs.
