### ISSUE TITLE
Update favicon

### ISSUE THREAD

**Issue by rgesulfo** [Greenstand/treetracker-admin-api#80]
Not urgent but low hanging fruit to make the admin panel even more 💯 
Here is the .ico file: https://drive.google.com/open?id=1Oi2znKp0_4FoKdJ_gkPRoUZenXh4zFIH
Thanks!

**Comment by Davidezrajay** [comment]
![favicon-16x16](https://user-images.githubusercontent.com/25363572/66683353-b703c980-ec23-11e9-912a-5f6a6964aca4.png)
![favicon-32x32](https://user-images.githubusercontent.com/25363572/66683355-b79c6000-ec23-11e9-9069-ff7bf9f77089.png)

**Comment by ghost** [comment]
> Not urgent but low hanging fruit to make the admin panel even more 💯
> Here is the .ico file: https://drive.google.com/open?id=1Oi2znKp0_4FoKdJ_gkPRoUZenXh4zFIH
> Thanks!

Hi, I couldn't find the link, it says ERROR 404. Would you help me check it?

**Comment by Davidezrajay** [comment]
Sorry, the link is broken. The files are in this ticket.
https://github.com/Greenstand/treetracker-admin/issues/80#issuecomment-541215149

**Comment by NickSiena** [comment]
![faviconTreeTracker](https://user-images.githubusercontent.com/37937337/70398449-9b315f80-19e9-11ea-8541-b0e5275f28f4.png)

**Comment by sjaymoon15** [comment]
Working on this rn. Will make a PR soon.

**Comment by Davidezrajay** [comment]
@sjaymoon15 Super awesome... thanks for you help!
