### ISSUE TITLE
Tagging of accept/reject reason via API

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/treetracker-admin-api#81]
A tree can be tagged blurry, hole dug, not a tree, etc.  We don't currently support this via the API.  I will add support for this so we can implement that tagging feature during review.

The field 'status' has been added to trees in the database and api.  Status is a string and can have the following values:

planted
hole
blurry
not-a-tree

A patch request (just like what is used for active and approved) can be used to update these values.

**Comment by dadiorchen** [comment]
Have been working on this ticket for a while, the rest story points estimate would be: 2 Hr
Current work looks below, if we need to adjust current requirements, please tell me as early as possible:
<img width="1141" alt="Screen Shot 2019-12-13 at 10 57 52 AM" src="https://user-images.githubusercontent.com/5744708/70766037-83fec300-1d97-11ea-9205-156136e3951c.png">

**Comment by dadiorchen** [comment]
is this ticket the same with #109 ?
