### ISSUE TITLE
API fails when accepting or rejecting a tree

### ISSUE THREAD

**Issue by rgesulfo** [Greenstand/treetracker-admin-api#87]
Here what I get when I click on the "Approve" button.
![image](https://user-images.githubusercontent.com/13984657/60151820-09af9780-9793-11e9-8524-3bbefa3b7e82.png)

**Comment by Davidezrajay** [comment]
@dadiorchen Can we close this.. It seems like you have this one fixed.

**Comment by dadiorchen** [comment]
I am not sure... can not reproduce this bug, but the approve and reject function works well now.
