### ISSUE TITLE
Reverse oder of trees to have oldest on the top. 

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-admin-api#91]
Currently new trees show first which is not logic since this is a queue. Older trees need to be approved/rejected first.

**Comment by sjaymoon15** [comment]
Working on this rn. Will submit a PR soon.

**Comment by sjaymoon15** [comment]
Should we close this issue now that we have made the change?
How does this process work here ?

**Comment by Davidezrajay** [comment]
@sjaymoon15 Thank you for this work!
